/*
 * SPDX-FileCopyrightText: Lucas Greuloch
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
package de.greluc.homeinv;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;
import tools.jackson.databind.json.JsonMapper;

/**
 * Nothing this artifact carries goes unattributed (REQ-CON-013).
 *
 * <h2>What this is for</h2>
 *
 * <p>A permissive licence — MIT, BSD, ISC, Apache-2.0 — permits the copying on one condition: that
 * its notice appears <b>in all copies</b>. The notice is generated by {@code tools/notices.py} from
 * what the boot jar carries, and CI regenerates it and fails on a difference. What that check
 * cannot see is whether the document is <i>complete</i>: a generator that quietly emitted a
 * component with no licence and no text would produce a file that matches itself perfectly.
 *
 * <p>So this reads the committed document and asks the three questions a licence breach would
 * answer wrongly.
 *
 * <h2>And the agreement with the SBOM</h2>
 *
 * <p>REQ-CON-013 asks for the SBOM of REQ-CON-010 and this notice to agree. They are two different
 * questions — the SBOM lists what the build resolved, the notice lists what the artifact carries —
 * so the rule is one-directional and has an escape hatch that has to be written down: a component
 * in the notice that the SBOM does not list needs a recorded reason under
 * {@code tools/notices/overrides/}. One component uses it, and finding it is why the rule exists:
 * Spring Boot's plugin puts {@code spring-boot-jarmode-tools} into the layered jar without it ever
 * being on the runtime classpath, so no SBOM mentions it and nothing else would have noticed.
 *
 * <p>No container, no Spring.
 */
@DisplayName("The third-party notice of this artifact")
class ThirdPartyNoticesTest {

  /** What the application serves, and carries in its jar. */
  private static final Path NOTICE = Path.of("src", "main", "resources", "third-party-notices.json");

  /** The bill of materials the same build produced (REQ-CON-010). */
  private static final Path SBOM = Path.of("build", "sbom", "home-inv-sbom.json");

  /** Where a component the SBOM does not list has its reason recorded. */
  private static final Path OVERRIDES = Path.of("..", "tools", "notices", "overrides", "maven");

  private static JsonNode notice;

  @BeforeAll
  static void read() throws IOException {
    ObjectMapper json = JsonMapper.builder().build();
    assertThat(NOTICE)
        .as(
            "This artifact carries no third-party licence notice. Run "
                + "`python tools/notices.py app`.")
        .exists();
    notice = json.readTree(Files.readString(NOTICE));
  }

  @Test
  @DisplayName("names a licence for every component in it")
  void everyComponentIsUnderSomething() {
    List<String> silent = new ArrayList<>();

    for (JsonNode component : notice.get("components")) {
      if (component.get("licences").isEmpty()) {
        silent.add(component.get("name").asString());
      }
    }

    assertThat(silent)
        .as("a component with no licence is one nobody may redistribute knowingly")
        .isEmpty();
  }

  @Test
  @DisplayName("carries the text of every licence it names")
  void everyLicenceHasItsWords() {
    Set<String> reproduced = new HashSet<>();
    for (JsonNode licence : notice.get("licences")) {
      assertThat(licence.get("text").asString())
          .as("the text of %s", licence.get("id").asString())
          .hasSizeGreaterThan(200);
      assertThat(licence.get("source").asString())
          .as("where the text of %s came from", licence.get("id").asString())
          .isNotBlank();
      reproduced.add(licence.get("id").asString());
    }

    List<String> unattributed = new ArrayList<>();
    for (JsonNode component : notice.get("components")) {
      boolean carriesItsOwn = !component.get("notices").isEmpty();
      boolean coveredByAppendix = false;
      for (JsonNode licence : component.get("licences")) {
        coveredByAppendix |= reproduced.contains(licence.asString());
      }
      if (!carriesItsOwn && !coveredByAppendix) {
        unattributed.add(component.get("name").asString());
      }
    }

    assertThat(unattributed)
        .as("a component whose licence text appears nowhere is an attribution that was not made")
        .isEmpty();
  }

  @Test
  @DisplayName("lists nothing the SBOM does not, unless the reason is recorded")
  void theSbomAndTheNoticeAgree() throws IOException {
    assertThat(SBOM)
        .as("no SBOM at %s — `./gradlew :app:test` depends on `cyclonedxDirectBom`", SBOM)
        .exists();
    JsonNode sbom = JsonMapper.builder().build().readTree(Files.readString(SBOM));
    Set<String> resolved = new HashSet<>();
    for (JsonNode component : sbom.get("components")) {
      resolved.add(component.get("name").asString());
    }

    Map<String, String> unexplained = new java.util.LinkedHashMap<>();
    for (JsonNode component : notice.get("components")) {
      String name = component.get("name").asString();
      if (resolved.contains(name) || Files.exists(OVERRIDES.resolve(name + ".txt"))) {
        continue;
      }
      unexplained.put(name, component.get("version").asString());
    }

    assertThat(unexplained)
        .as(
            "the notice lists a component the SBOM does not, and nothing says why. Record it in "
                + "tools/notices/overrides/maven/<name>.txt, which is where the reason belongs")
        .isEmpty();
  }
}
