/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * What accepting an invitation produced.
 *
 * @param accountCreated whether this acceptance created the account, which decides whether the client sends the person to a sign-in or straight on
 * @param role the role granted
 * @param tenantId the tenant joined
 * @param tenantName its display name, so the client can say where the person has landed
 * @param userId the account, whether it existed or was created by this acceptance
 */
@Serializable

data class AcceptedInvitation (

    /* whether this acceptance created the account, which decides whether the client sends the person to a sign-in or straight on */
    @SerialName(value = "accountCreated") @Required val accountCreated: kotlin.Boolean,

    /* the role granted */
    @SerialName(value = "role") @Required val role: kotlin.String,

    /* the tenant joined */
    @SerialName(value = "tenantId") @Required val tenantId: kotlin.String,

    /* its display name, so the client can say where the person has landed */
    @SerialName(value = "tenantName") @Required val tenantName: kotlin.String,

    /* the account, whether it existed or was created by this acceptance */
    @SerialName(value = "userId") @Required val userId: kotlin.String

) {


}

