/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The body of an acceptance.
 *
 * @param displayName what the interface should call the new account; ignored when the address already has one
 * @param locale the interface language to start in; ignored when the account exists
 * @param password the new account's password. Length-bounded for the reason the login's is: Argon2id spends 19 MiB per hash, and an unbounded field is an invitation to spend it on a megabyte of nothing
 */
@Serializable

data class AcceptRequest (

    /* what the interface should call the new account; ignored when the address already has one */
    @SerialName(value = "displayName") val displayName: kotlin.String? = null,

    /* the interface language to start in; ignored when the account exists */
    @SerialName(value = "locale") val locale: kotlin.String? = null,

    /* the new account's password. Length-bounded for the reason the login's is: Argon2id spends 19 MiB per hash, and an unbounded field is an invitation to spend it on a megabyte of nothing */
    @SerialName(value = "password") val password: kotlin.String? = null

) {


}

