/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * An account as the operator's view shows it.  No password hash, no session information, no list of tenants: an operator administers entitlements, and the rest is the account holder's.
 *
 * @param displayName what the interface calls them
 * @param email the login address
 * @param id the account
 * @param instanceOperator whether they administer the instance
 * @param locked whether the account is barred from authenticating
 * @param mayCreateTenants whether they may create tenants
 * @param tenantLimit their own limit, or null when the instance-wide default applies
 */
@Serializable

data class AccountView (

    /* what the interface calls them */
    @SerialName(value = "displayName") @Required val displayName: kotlin.String,

    /* the login address */
    @SerialName(value = "email") @Required val email: kotlin.String,

    /* the account */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* whether they administer the instance */
    @SerialName(value = "instanceOperator") @Required val instanceOperator: kotlin.Boolean,

    /* whether the account is barred from authenticating */
    @SerialName(value = "locked") @Required val locked: kotlin.Boolean,

    /* whether they may create tenants */
    @SerialName(value = "mayCreateTenants") @Required val mayCreateTenants: kotlin.Boolean,

    /* their own limit, or null when the instance-wide default applies */
    @SerialName(value = "tenantLimit") @Required val tenantLimit: kotlin.Int?

) {


}

