/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * What a client asks for when it starts a flow.
 *
 * @param loginHint an address to prefill at the provider, or null
 * @param returnTo a path on this instance to return to, or null
 */
@Serializable

data class BeginRequest (

    /* an address to prefill at the provider, or null */
    @SerialName(value = "loginHint") val loginHint: kotlin.String? = null,

    /* a path on this instance to return to, or null */
    @SerialName(value = "returnTo") val returnTo: kotlin.String? = null

) {


}

