/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * What a client is told about this build.
 *
 * @param builtAt when it was built, or `null` when the build carried no information
 * @param commit the exact commit it was built from, or `unknown` where the build had no git directory and was given no override
 * @param licence the licence the source is under, so a reader knows what the offer is about
 * @param source where the source is
 * @param version the application's own version
 */
@Serializable

data class BuildVersion (

    /* when it was built, or `null` when the build carried no information */
    @SerialName(value = "builtAt") @Required val builtAt: kotlin.time.Instant,

    /* the exact commit it was built from, or `unknown` where the build had no git directory and was given no override */
    @SerialName(value = "commit") @Required val commit: kotlin.String,

    /* the licence the source is under, so a reader knows what the offer is about */
    @SerialName(value = "licence") @Required val licence: kotlin.String,

    /* where the source is */
    @SerialName(value = "source") @Required val source: kotlin.String,

    /* the application's own version */
    @SerialName(value = "version") @Required val version: kotlin.String

) {


}

