/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models

import de.greluc.homeinv.client.models.BulkEntryRequest

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * One change, its target, and the items it applies to.
 *
 * @param propertyEntries the items, at most 500
 * @param operation which of the four
 * @param itemTypeId the type a change of type writes them against
 * @param locationId where a move puts them
 * @param tagId what a tag assignment assigns
 */
@Serializable

data class BulkRequest (

    /* the items, at most 500 */
    @SerialName(value = "entries") @Required val propertyEntries: kotlin.collections.List<BulkEntryRequest>,

    /* which of the four */
    @SerialName(value = "operation") @Required val operation: BulkRequest.Operation,

    /* the type a change of type writes them against */
    @SerialName(value = "itemTypeId") val itemTypeId: kotlin.String? = null,

    /* where a move puts them */
    @SerialName(value = "locationId") val locationId: kotlin.String? = null,

    /* what a tag assignment assigns */
    @SerialName(value = "tagId") val tagId: kotlin.String? = null

) {

    /**
     * which of the four
     *
     * Values: MOVE,TAG,CHANGE_TYPE,DELETE
     */
    @Serializable
    enum class Operation(val value: kotlin.String) {
        @SerialName(value = "MOVE") MOVE("MOVE"),
        @SerialName(value = "TAG") TAG("TAG"),
        @SerialName(value = "CHANGE_TYPE") CHANGE_TYPE("CHANGE_TYPE"),
        @SerialName(value = "DELETE") DELETE("DELETE");
        override fun toString(): kotlin.String = value
    }

}

