/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * What became of one entry.
 *
 * @param detail what went wrong in prose, or `null` when nothing did
 * @param itemId the item this line is about
 * @param status the status this entry would have had as a request of its own
 * @param title the stable name of the condition, or `null` when the entry was applied
 * @param type the problem type URI, or `null` when the entry was applied
 */
@Serializable

data class BulkEntryStatus (

    /* what went wrong in prose, or `null` when nothing did */
    @SerialName(value = "detail") @Required val detail: kotlin.String,

    /* the item this line is about */
    @SerialName(value = "itemId") @Required val itemId: kotlin.String,

    /* the status this entry would have had as a request of its own */
    @SerialName(value = "status") @Required val status: kotlin.Int,

    /* the stable name of the condition, or `null` when the entry was applied */
    @SerialName(value = "title") @Required val title: kotlin.String,

    /* the problem type URI, or `null` when the entry was applied */
    @SerialName(value = "type") @Required val type: kotlin.String

) {


}

