/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * One capability a plugin asks for.
 *
 * @param granted whether this tenant has agreed to it. False is the state every capability starts in: a plugin has no permissions until they are granted
 * @param id the capability, from the closed set of 09 §9.4
 */
@Serializable

data class CapabilityView (

    /* whether this tenant has agreed to it. False is the state every capability starts in: a plugin has no permissions until they are granted */
    @SerialName(value = "granted") @Required val granted: kotlin.Boolean,

    /* the capability, from the closed set of 09 §9.4 */
    @SerialName(value = "id") @Required val id: kotlin.String

) {


}

