/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A location category as an administrator sees it.
 *
 * @param archived whether it is offered for nothing new
 * @param builtin whether it was provisioned with the tenant
 * @param draftVersionId the version being edited, or `null`
 * @param icon an icon name for the client, or `null`
 * @param id the category
 * @param key its stable key
 * @param labels its name per language tag
 * @param mobile whether its locations travel with their contents
 * @param publishedVersionId the newest published version, or `null`
 */
@Serializable

data class CategoryView (

    /* whether it is offered for nothing new */
    @SerialName(value = "archived") @Required val archived: kotlin.Boolean,

    /* whether it was provisioned with the tenant */
    @SerialName(value = "builtin") @Required val builtin: kotlin.Boolean,

    /* the version being edited, or `null` */
    @SerialName(value = "draftVersionId") @Required val draftVersionId: kotlin.String,

    /* an icon name for the client, or `null` */
    @SerialName(value = "icon") @Required val icon: kotlin.String,

    /* the category */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* its stable key */
    @SerialName(value = "key") @Required val key: kotlin.String,

    /* its name per language tag */
    @SerialName(value = "labels") @Required val labels: kotlin.collections.Map<kotlin.String, kotlin.String>,

    /* whether its locations travel with their contents */
    @SerialName(value = "mobile") @Required val mobile: kotlin.Boolean,

    /* the newest published version, or `null` */
    @SerialName(value = "publishedVersionId") @Required val publishedVersionId: kotlin.String

) {


}

