/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The options one side of a ceremony needs.
 *
 * @param options the WebAuthn options, as the JSON `navigator.credentials` takes. Passed through as text rather than re-modelled: the shape is the specification's, and a second model of it here would be a second thing to keep in step with browsers
 */
@Serializable

data class CeremonyView (

    /* the WebAuthn options, as the JSON `navigator.credentials` takes. Passed through as text rather than re-modelled: the shape is the specification's, and a second model of it here would be a second thing to keep in step with browsers */
    @SerialName(value = "options") @Required val options: kotlin.String

) {


}

