/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models

import de.greluc.homeinv.client.models.BlockReport

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * One certificate.
 *
 * @param completedAt when the last block reported
 * @param report one entry per building block: how many rows it removed, and where something was deliberately left, why
 * @param requestedAt when the erasure was asked for
 * @param requestedBy which account asked. An opaque id and nothing more, which is what 05 §5.9 means by keeping the record \"pseudonymised\"
 * @param tenantId the tenant that was erased
 * @param tenantName what it was called, as it stood when the erasure began
 */
@Serializable

data class Certificate (

    /* when the last block reported */
    @SerialName(value = "completedAt") @Required val completedAt: kotlin.time.Instant,

    /* one entry per building block: how many rows it removed, and where something was deliberately left, why */
    @SerialName(value = "report") @Required val report: kotlin.collections.List<BlockReport>,

    /* when the erasure was asked for */
    @SerialName(value = "requestedAt") @Required val requestedAt: kotlin.time.Instant,

    /* which account asked. An opaque id and nothing more, which is what 05 §5.9 means by keeping the record \"pseudonymised\" */
    @SerialName(value = "requestedBy") @Required val requestedBy: kotlin.String,

    /* the tenant that was erased */
    @SerialName(value = "tenantId") @Required val tenantId: kotlin.String,

    /* what it was called, as it stood when the erasure began */
    @SerialName(value = "tenantName") @Required val tenantName: kotlin.String

) {


}

