/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * What one category takes underneath it (REQ-CORE-047).  No cursor and no page, and that is deliberate: the list is the rule itself, and half a whitelist is not a smaller answer but a wrong one. It cannot outgrow the tenant's categories, which is a configuration surface a person maintains by hand — the write caps it at 200 anyway, for the reason every collection here is capped.
 *
 * @param categoryId the category the rule belongs to
 * @param permitted the categories it takes, by id, ordered by when each was permitted. Empty means no restriction at all and therefore everything, not nothing
 */
@Serializable

data class ChildCategoryRuleView (

    /* the category the rule belongs to */
    @SerialName(value = "categoryId") @Required val categoryId: kotlin.String,

    /* the categories it takes, by id, ordered by when each was permitted. Empty means no restriction at all and therefore everything, not nothing */
    @SerialName(value = "permitted") @Required val permitted: kotlin.collections.List<kotlin.String>

) {


}

