/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The categories a category is to take underneath it (REQ-CORE-047).
 *
 * @param permitted the categories, by id. Omitted or empty withdraws the restriction, so the category takes everything again; the cap is the one every collection here carries
 */
@Serializable

data class ChildCategoriesRequest (

    /* the categories, by id. Omitted or empty withdraws the restriction, so the category takes everything again; the cap is the one every collection here carries */
    @SerialName(value = "permitted") val permitted: kotlin.collections.List<kotlin.String>? = null

) {


}

