/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The body of a creation.
 *
 * @param categoryId the category
 * @param name the name
 * @param attributes the fields the category declares, as a JSON object. Checked against the category version's schema, and an offending value is a `422` naming its path (REQ-CORE-041, REQ-CORE-005)
 * @param id the client's chosen id, or omitted
 * @param parentId the parent, or omitted to create a root
 */
@Serializable

data class CreateLocationRequest (

    /* the category */
    @SerialName(value = "categoryId") @Required val categoryId: kotlin.String,

    /* the name */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* the fields the category declares, as a JSON object. Checked against the category version's schema, and an offending value is a `422` naming its path (REQ-CORE-041, REQ-CORE-005) */
    @SerialName(value = "attributes") val attributes: kotlin.String? = null,

    /* the client's chosen id, or omitted */
    @SerialName(value = "id") val id: kotlin.String? = null,

    /* the parent, or omitted to create a root */
    @SerialName(value = "parentId") val parentId: kotlin.String? = null

) {


}

