/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The body of a tenant creation.
 *
 * @param name what to call it. The only thing a new tenant needs: everything else it has — the built-in item type, the location categories — is seeded for it
 */
@Serializable

data class CreateTenantRequest (

    /* what to call it. The only thing a new tenant needs: everything else it has — the built-in item type, the location categories — is seeded for it */
    @SerialName(value = "name") @Required val name: kotlin.String

) {


}

