/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * What to call a new value list.
 *
 * @param key the stable key
 * @param labels the list's name per language tag
 */
@Serializable

data class CreateValueListRequest (

    /* the stable key */
    @SerialName(value = "key") @Required val key: kotlin.String,

    /* the list's name per language tag */
    @SerialName(value = "labels") val labels: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {


}

