/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * What an erasure request produced.
 *
 * @param eraseAfter when the grace period runs out and the erasure begins
 * @param revocationToken the secret that withdraws it. Returned **once**: where `plugin-smtp` is installed it also goes out by mail, and where it is not — which a `minimal` installation is by design — this is the only way it reaches anybody
 */
@Serializable

data class DeletionRequest (

    /* when the grace period runs out and the erasure begins */
    @SerialName(value = "eraseAfter") @Required val eraseAfter: kotlin.time.Instant,

    /* the secret that withdraws it. Returned **once**: where `plugin-smtp` is installed it also goes out by mail, and where it is not — which a `minimal` installation is by design — this is the only way it reaches anybody */
    @SerialName(value = "revocationToken") @Required val revocationToken: kotlin.String

) {


}

