/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models

import de.greluc.homeinv.client.models.MoneyJson

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The body of a disposal (REQ-LIFE-007).
 *
 * @param on when it went
 * @param state `SOLD` or `DISPOSED` — the two ways an item leaves. Any other value is refused rather than treated as a disposal
 * @param note anything else worth knowing, or absent
 * @param price what it fetched, or absent. Only a sale has one; absent rather than zero for something given away, because the two are different claims
 * @param recipient who to, in the seller's own words, or absent
 */
@Serializable

data class DisposalRequest (

    /* when it went */
    @SerialName(value = "on") @Required val on: kotlinx.datetime.LocalDate,

    /* `SOLD` or `DISPOSED` — the two ways an item leaves. Any other value is refused rather than treated as a disposal */
    @SerialName(value = "state") @Required val state: DisposalRequest.State,

    /* anything else worth knowing, or absent */
    @SerialName(value = "note") val note: kotlin.String? = null,

    /* what it fetched, or absent. Only a sale has one; absent rather than zero for something given away, because the two are different claims */
    @SerialName(value = "price") val price: MoneyJson? = null,

    /* who to, in the seller's own words, or absent */
    @SerialName(value = "recipient") val recipient: kotlin.String? = null

) {

    /**
     * `SOLD` or `DISPOSED` — the two ways an item leaves. Any other value is refused rather than treated as a disposal
     *
     * Values: ACTIVE,LENT,ARCHIVED,TRASHED,SOLD,DISPOSED
     */
    @Serializable
    enum class State(val value: kotlin.String) {
        @SerialName(value = "ACTIVE") ACTIVE("ACTIVE"),
        @SerialName(value = "LENT") LENT("LENT"),
        @SerialName(value = "ARCHIVED") ARCHIVED("ARCHIVED"),
        @SerialName(value = "TRASHED") TRASHED("TRASHED"),
        @SerialName(value = "SOLD") SOLD("SOLD"),
        @SerialName(value = "DISPOSED") DISPOSED("DISPOSED");
        override fun toString(): kotlin.String = value
    }

}

