/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models

import de.greluc.homeinv.client.models.PasskeyView

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * What an account holds.
 *
 * @param enrolledAt when it was confirmed, or null
 * @param passkeys the registered passkeys, oldest first
 * @param recoveryCodesLeft how many single-use codes are unspent. Zero beside a confirmed factor is worth showing: losing the phone then loses the account
 * @param totpConfirmed whether a confirmed authenticator app exists
 */
@Serializable

data class EnrolmentView (

    /* when it was confirmed, or null */
    @SerialName(value = "enrolledAt") @Required val enrolledAt: kotlin.time.Instant,

    /* the registered passkeys, oldest first */
    @SerialName(value = "passkeys") @Required val passkeys: kotlin.collections.List<PasskeyView>,

    /* how many single-use codes are unspent. Zero beside a confirmed factor is worth showing: losing the phone then loses the account */
    @SerialName(value = "recoveryCodesLeft") @Required val recoveryCodesLeft: kotlin.Int,

    /* whether a confirmed authenticator app exists */
    @SerialName(value = "totpConfirmed") @Required val totpConfirmed: kotlin.Boolean

) {


}

