/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The body of an entitlement change.
 *
 * @param instanceOperator whether the account administers the instance
 * @param mayCreateTenants whether it may create tenants (REQ-TEN-002)
 * @param tenantLimit how many tenants it may be in, or omitted for the instance-wide default
 */
@Serializable

data class EntitlementsRequest (

    /* whether the account administers the instance */
    @SerialName(value = "instanceOperator") val instanceOperator: kotlin.Boolean? = null,

    /* whether it may create tenants (REQ-TEN-002) */
    @SerialName(value = "mayCreateTenants") val mayCreateTenants: kotlin.Boolean? = null,

    /* how many tenants it may be in, or omitted for the instance-wide default */
    @SerialName(value = "tenantLimit") val tenantLimit: kotlin.Int? = null

) {


}

