/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A file that backs a line up.
 *
 * @param byteSize how large
 * @param mediaObjectId which file
 * @param mediaType what it is
 * @param role what the tenant said it was for
 */
@Serializable

data class Evidence (

    /* how large */
    @SerialName(value = "byteSize") @Required val byteSize: kotlin.Long,

    /* which file */
    @SerialName(value = "mediaObjectId") @Required val mediaObjectId: kotlin.String,

    /* what it is */
    @SerialName(value = "mediaType") @Required val mediaType: kotlin.String,

    /* what the tenant said it was for */
    @SerialName(value = "role") @Required val role: kotlin.String

) {


}

