/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * One thing that runs out.
 *
 * @param dueOn when it runs out
 * @param itemId which item
 * @param itemName what it is called
 * @param kind `warranty` for the column, or the field's key for an attribute — so a client can group by it and a person can see *what* runs out rather than only when
 * @param label what to call the kind in the tenant's language, or the field key when the field declares no label
 */
@Serializable

data class Expiring (

    /* when it runs out */
    @SerialName(value = "dueOn") @Required val dueOn: kotlinx.datetime.LocalDate,

    /* which item */
    @SerialName(value = "itemId") @Required val itemId: kotlin.String,

    /* what it is called */
    @SerialName(value = "itemName") @Required val itemName: kotlin.String,

    /* `warranty` for the column, or the field's key for an attribute — so a client can group by it and a person can see *what* runs out rather than only when */
    @SerialName(value = "kind") @Required val kind: kotlin.String,

    /* what to call the kind in the tenant's language, or the field key when the field declares no label */
    @SerialName(value = "label") @Required val label: kotlin.String

) {


}

