/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * An export job as a caller sees it.
 *
 * @param byteSize how large the archive is, or `null` until it exists
 * @param failure what went wrong, or `null`. Never a stack trace: it is shown to whoever asked
 * @param finishedAt when it finished, or `null`
 * @param id its id
 * @param progress how far along, 0 to 100 — coarse on purpose, because it is read by somebody deciding whether to keep waiting and a number that moves is worth more to them than a number that is exact
 * @param ready Whether the archive can be downloaded.
 * @param requestedAt when it was asked for
 * @param requestedBy who asked
 * @param state `QUEUED`, `RUNNING`, `READY` or `FAILED`
 */
@Serializable

data class ExportJobView (

    /* how large the archive is, or `null` until it exists */
    @SerialName(value = "byteSize") @Required val byteSize: kotlin.Long,

    /* what went wrong, or `null`. Never a stack trace: it is shown to whoever asked */
    @SerialName(value = "failure") @Required val failure: kotlin.String,

    /* when it finished, or `null` */
    @SerialName(value = "finishedAt") @Required val finishedAt: kotlin.time.Instant,

    /* its id */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* how far along, 0 to 100 — coarse on purpose, because it is read by somebody deciding whether to keep waiting and a number that moves is worth more to them than a number that is exact */
    @SerialName(value = "progress") @Required val progress: kotlin.Int,

    /* Whether the archive can be downloaded. */
    @SerialName(value = "ready") @Required val ready: kotlin.Boolean,

    /* when it was asked for */
    @SerialName(value = "requestedAt") @Required val requestedAt: kotlin.time.Instant,

    /* who asked */
    @SerialName(value = "requestedBy") @Required val requestedBy: kotlin.String,

    /* `QUEUED`, `RUNNING`, `READY` or `FAILED` */
    @SerialName(value = "state") @Required val state: kotlin.String

) {


}

