/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models

import de.greluc.homeinv.client.models.Bucket

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * How many rows a list would still hold for each value of one dimension (REQ-SRCH-002).  The sidebar beside a list: \"Werkzeug 41, Buch 12\", \"defekt 4\", \"Schuppen 18\". A client renders the buckets and puts a bucket's {@link Bucket#value Bucket#value()} straight back into a `filter` parameter — which is why a bucket carries the token the filter grammar takes and not a display name. A type is its key, a tag its name, a location its id, an attribute its stored value; the names come from the endpoints that own them, because a count is not the place to learn what something is called in a language.  ## A facet is counted without its own filter  Decided with the owner on 2026-09-14. With `filter=tag:broken` active, the tag facet still counts every tag — \"neu 12, gebraucht 30, defekt 4\" — because the whole point of the sidebar is to show where one could click next. Counted *with* its own filter it would show one tag and the total, which is a number nobody needs and a control nobody can use. Every *other* dimension's filters do narrow it, so the counts still describe the list somebody is looking at.  That makes \"facet counts agree with the results\" true of a dimension nobody filtered by and deliberately untrue of one somebody did. REQ-SRCH-002's acceptance says so since that decision.
 *
 * @param buckets the values and their counts, most first
 * @param dimension what was counted, spelled as the `facet` and `filter` parameters spell it: `type`, `category`, `tag`, `location` or `attr.<key>`
 */
@Serializable

data class Facet (

    /* the values and their counts, most first */
    @SerialName(value = "buckets") @Required val buckets: kotlin.collections.List<Bucket>,

    /* what was counted, spelled as the `facet` and `filter` parameters spell it: `type`, `category`, `tag`, `location` or `attr.<key>` */
    @SerialName(value = "dimension") @Required val dimension: kotlin.String

) {


}

