/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models

import de.greluc.homeinv.client.models.FieldConstraints
import de.greluc.homeinv.client.models.VisibilityRule

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * One field of one type version, as everything outside `catalog` sees it.  A view and not the entity (REQ-NFR-022): `inventory` needs to know that ` purchasePrice` is money and is searchable; it has no business holding a row it could write back.
 *
 * @param constraints the declarative limits, never `null` — {@link FieldConstraints#NONE FieldConstraints#NONE} when the definition carries none
 * @param dataType what kind of value it holds
 * @param defaultValue the JSON text of the value a new item starts with, or `null`
 * @param deprecated whether it is hidden from new input while its values remain (REQ-CORE-026)
 * @param displayOrder the position within that group; ties are broken by key, so the order is total
 * @param expiry whether this date is an expiry, and so appears in the overview of REQ-LIFE-013
 * @param facetable whether it is mirrored for counting
 * @param group the form section the tenant put it in, or `null`
 * @param helpTexts the explanatory line per language tag, empty when the tenant wrote none
 * @param id the definition, stable across the life of the version it belongs to
 * @param key the attribute key — `isbn`, `purchasePrice` — which is what appears in `item.attributes` and in `item_attr_index.field_key`
 * @param labels the field's name per language tag, as the tenant wrote it. Multilingual data rather than interface text: the server cannot translate a word a tenant invented (REQ-NFR-032)
 * @param required whether a value must be present. A deprecated field is never required, whatever this says — see {@link de.greluc.homeinv.catalog.api.FieldDefinitionView#effectivelyRequired #effectivelyRequired()}
 * @param searchable whether it is mirrored into the side table for filtering
 * @param sensitive whether reading it needs a permission of its own and it is encrypted at rest (ADR-0019)
 * @param sortable whether it is mirrored for ordering
 * @param valueListId the list an `enum` or `multi-enum` draws from, `null` otherwise
 * @param visibility the one condition that decides whether a client shows this field, or ` null` when it is always shown
 */
@Serializable

data class FieldDefinitionView (

    /* the declarative limits, never `null` — {@link FieldConstraints#NONE FieldConstraints#NONE} when the definition carries none */
    @SerialName(value = "constraints") @Required val constraints: FieldConstraints,

    /* what kind of value it holds */
    @SerialName(value = "dataType") @Required val dataType: FieldDefinitionView.DataType,

    /* the JSON text of the value a new item starts with, or `null` */
    @SerialName(value = "defaultValue") @Required val defaultValue: kotlin.String?,

    /* whether it is hidden from new input while its values remain (REQ-CORE-026) */
    @SerialName(value = "deprecated") @Required val deprecated: kotlin.Boolean,

    /* the position within that group; ties are broken by key, so the order is total */
    @SerialName(value = "displayOrder") @Required val displayOrder: kotlin.Int,

    /* whether this date is an expiry, and so appears in the overview of REQ-LIFE-013 */
    @SerialName(value = "expiry") @Required val expiry: kotlin.Boolean,

    /* whether it is mirrored for counting */
    @SerialName(value = "facetable") @Required val facetable: kotlin.Boolean,

    /* the form section the tenant put it in, or `null` */
    @SerialName(value = "group") @Required val group: kotlin.String?,

    /* the explanatory line per language tag, empty when the tenant wrote none */
    @SerialName(value = "helpTexts") @Required val helpTexts: kotlin.collections.Map<kotlin.String, kotlin.String>,

    /* the definition, stable across the life of the version it belongs to */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* the attribute key — `isbn`, `purchasePrice` — which is what appears in `item.attributes` and in `item_attr_index.field_key` */
    @SerialName(value = "key") @Required val key: kotlin.String,

    /* the field's name per language tag, as the tenant wrote it. Multilingual data rather than interface text: the server cannot translate a word a tenant invented (REQ-NFR-032) */
    @SerialName(value = "labels") @Required val labels: kotlin.collections.Map<kotlin.String, kotlin.String>,

    /* whether a value must be present. A deprecated field is never required, whatever this says — see {@link de.greluc.homeinv.catalog.api.FieldDefinitionView#effectivelyRequired #effectivelyRequired()} */
    @SerialName(value = "required") @Required val required: kotlin.Boolean,

    /* whether it is mirrored into the side table for filtering */
    @SerialName(value = "searchable") @Required val searchable: kotlin.Boolean,

    /* whether reading it needs a permission of its own and it is encrypted at rest (ADR-0019) */
    @SerialName(value = "sensitive") @Required val sensitive: kotlin.Boolean,

    /* whether it is mirrored for ordering */
    @SerialName(value = "sortable") @Required val sortable: kotlin.Boolean,

    /* the list an `enum` or `multi-enum` draws from, `null` otherwise */
    @SerialName(value = "valueListId") @Required val valueListId: kotlin.String?,

    /* the one condition that decides whether a client shows this field, or ` null` when it is always shown */
    @SerialName(value = "visibility") @Required val visibility: VisibilityRule

) {

    /**
     * what kind of value it holds
     *
     * Values: TEXT,MULTILINE,INTEGER,DECIMAL,MONEY,BOOLEAN,DATE,DATETIME,ENUM,MULTI_ENUM,URL,EMAIL,QUANTITY,REFERENCE,SECRET,FILE
     */
    @Serializable
    enum class DataType(val value: kotlin.String) {
        @SerialName(value = "TEXT") TEXT("TEXT"),
        @SerialName(value = "MULTILINE") MULTILINE("MULTILINE"),
        @SerialName(value = "INTEGER") INTEGER("INTEGER"),
        @SerialName(value = "DECIMAL") DECIMAL("DECIMAL"),
        @SerialName(value = "MONEY") MONEY("MONEY"),
        @SerialName(value = "BOOLEAN") BOOLEAN("BOOLEAN"),
        @SerialName(value = "DATE") DATE("DATE"),
        @SerialName(value = "DATETIME") DATETIME("DATETIME"),
        @SerialName(value = "ENUM") ENUM("ENUM"),
        @SerialName(value = "MULTI_ENUM") MULTI_ENUM("MULTI_ENUM"),
        @SerialName(value = "URL") URL("URL"),
        @SerialName(value = "EMAIL") EMAIL("EMAIL"),
        @SerialName(value = "QUANTITY") QUANTITY("QUANTITY"),
        @SerialName(value = "REFERENCE") REFERENCE("REFERENCE"),
        @SerialName(value = "SECRET") SECRET("SECRET"),
        @SerialName(value = "FILE") FILE("FILE");
        override fun toString(): kotlin.String = value
    }

}

