/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * What a field removal would destroy (REQ-CORE-026).
 *
 * @param affected how many items or locations carry a value under that key today
 * @param fieldId the field
 * @param key its attribute key
 */
@Serializable

data class FieldRemovalPreview (

    /* how many items or locations carry a value under that key today */
    @SerialName(value = "affected") @Required val affected: kotlin.Long,

    /* the field */
    @SerialName(value = "fieldId") @Required val fieldId: kotlin.String,

    /* its attribute key */
    @SerialName(value = "key") @Required val key: kotlin.String

) {


}

