/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models

import de.greluc.homeinv.client.models.RoleReference

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Which roles may read one field.
 *
 * @param fieldKey the field, as its type declares it
 * @param roles the roles permitted to read it, possibly none — which is a rule for nobody and not the absence of a rule
 */
@Serializable

data class FieldRules (

    /* the field, as its type declares it */
    @SerialName(value = "fieldKey") @Required val fieldKey: kotlin.String,

    /* the roles permitted to read it, possibly none — which is a rule for nobody and not the absence of a rule */
    @SerialName(value = "roles") @Required val roles: kotlin.collections.List<RoleReference>

) {


}

