/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The body of a grant.
 *
 * @param fieldKey the field's key, as the type system spells it
 * @param role the built-in role to grant it to, or omitted when a tenant-owned one is named
 * @param roleDefinitionId the tenant-owned role to grant it to, or omitted
 */
@Serializable

data class FieldVisibilityRequest (

    /* the field's key, as the type system spells it */
    @SerialName(value = "fieldKey") @Required val fieldKey: kotlin.String,

    /* the built-in role to grant it to, or omitted when a tenant-owned one is named */
    @SerialName(value = "role") val role: kotlin.String? = null,

    /* the tenant-owned role to grant it to, or omitted */
    @SerialName(value = "roleDefinitionId") val roleDefinitionId: kotlin.String? = null

) {


}

