/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * An import job as a caller sees it.
 *
 * @param byteSize how large the uploaded archive was
 * @param dryRun whether the work was thrown away at the end
 * @param failure what went wrong, or null. One sentence, never a stack trace
 * @param finishedAt when it ended, or null
 * @param id its id
 * @param progress how far along, 0 to 100
 * @param report what happened, as a JSON object, or null until the job finishes. Per block: how many rows were inserted, how many overwritten and how many deliberately skipped, plus the sentences saying what an import never writes
 * @param requestedAt when it was uploaded
 * @param state `QUEUED`, `RUNNING`, `DONE` or `FAILED`
 */
@Serializable

data class ImportJobView (

    /* how large the uploaded archive was */
    @SerialName(value = "byteSize") @Required val byteSize: kotlin.Long,

    /* whether the work was thrown away at the end */
    @SerialName(value = "dryRun") @Required val dryRun: kotlin.Boolean,

    /* what went wrong, or null. One sentence, never a stack trace */
    @SerialName(value = "failure") @Required val failure: kotlin.String?,

    /* when it ended, or null */
    @SerialName(value = "finishedAt") @Required val finishedAt: kotlin.time.Instant?,

    /* its id */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* how far along, 0 to 100 */
    @SerialName(value = "progress") @Required val progress: kotlin.Int,

    /* what happened, as a JSON object, or null until the job finishes. Per block: how many rows were inserted, how many overwritten and how many deliberately skipped, plus the sentences saying what an import never writes */
    @SerialName(value = "report") @Required val report: kotlin.String?,

    /* when it was uploaded */
    @SerialName(value = "requestedAt") @Required val requestedAt: kotlin.time.Instant,

    /* `QUEUED`, `RUNNING`, `DONE` or `FAILED` */
    @SerialName(value = "state") @Required val state: kotlin.String

) {


}

