/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models

import de.greluc.homeinv.client.models.InstanceCapabilityView

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * An installed plugin as the operator sees it.
 *
 * @param capabilities everything its manifest asks for, each with whether the **instance** has granted it. A tenant's grants are not shown here and are not this surface's business
 * @param disabled whether it is out of service
 * @param id its reverse-domain id
 * @param name what a person sees
 * @param registeredAt when it was first seen
 * @param signed whether this core verified its manifest signature against the public key the operator installed for it (REQ-PLG-004, ADR-0085)
 * @param stateReason why it is in that state, in a sentence, or null when there is nothing to say. This is the operator's surface, and a plugin taken out of service by its signature is exactly the case where \"disabled\" on its own tells them nothing they can act on — an altered manifest and a publisher who never signed are different problems with different answers
 * @param version the plugin's own version
 */
@Serializable

data class InstancePluginView (

    /* everything its manifest asks for, each with whether the **instance** has granted it. A tenant's grants are not shown here and are not this surface's business */
    @SerialName(value = "capabilities") @Required val capabilities: kotlin.collections.List<InstanceCapabilityView>,

    /* whether it is out of service */
    @SerialName(value = "disabled") @Required val disabled: kotlin.Boolean,

    /* its reverse-domain id */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* what a person sees */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* when it was first seen */
    @SerialName(value = "registeredAt") @Required val registeredAt: kotlin.time.Instant,

    /* whether this core verified its manifest signature against the public key the operator installed for it (REQ-PLG-004, ADR-0085) */
    @SerialName(value = "signed") @Required val signed: kotlin.Boolean,

    /* why it is in that state, in a sentence, or null when there is nothing to say. This is the operator's surface, and a plugin taken out of service by its signature is exactly the case where \"disabled\" on its own tells them nothing they can act on — an altered manifest and a publisher who never signed are different problems with different answers */
    @SerialName(value = "stateReason") @Required val stateReason: kotlin.String?,

    /* the plugin's own version */
    @SerialName(value = "version") @Required val version: kotlin.String

) {


}

