/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The body of an invitation.
 *
 * @param email the address to invite, which the invitation is bound to
 * @param role the role to grant on acceptance, bounded by what the inviter holds (REQ-TEN-010)
 */
@Serializable

data class InviteRequest (

    /* the address to invite, which the invitation is bound to */
    @SerialName(value = "email") @Required val email: kotlin.String,

    /* the role to grant on acceptance, bounded by what the inviter holds (REQ-TEN-010) */
    @SerialName(value = "role") @Required val role: kotlin.String

) {


}

