/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * An invitation, as the tenant that issued it sees it.  The token is not here. It exists once, in the answer to {@link de.greluc.homeinv.tenancy.api.InvitationService.InvitationView#invite #invite}, and afterwards only as a hash (REQ-SEC-048) — so a list of invitations cannot be read to obtain one, and an administrator who loses a link withdraws it and sends another.
 *
 * @param email the address it is bound to
 * @param expiresAt when it stops working
 * @param id the invitation
 * @param invitedAt when it was issued
 * @param role the role it grants on acceptance
 * @param state `OPEN`, `ACCEPTED`, `REVOKED` or `EXPIRED`
 */
@Serializable

data class InvitationView (

    /* the address it is bound to */
    @SerialName(value = "email") @Required val email: kotlin.String,

    /* when it stops working */
    @SerialName(value = "expiresAt") @Required val expiresAt: kotlin.time.Instant,

    /* the invitation */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* when it was issued */
    @SerialName(value = "invitedAt") @Required val invitedAt: kotlin.time.Instant,

    /* the role it grants on acceptance */
    @SerialName(value = "role") @Required val role: kotlin.String,

    /* `OPEN`, `ACCEPTED`, `REVOKED` or `EXPIRED` */
    @SerialName(value = "state") @Required val state: kotlin.String

) {


}

