/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models

import de.greluc.homeinv.client.models.ServiceAccountView

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A service account that has just been created, and its token.
 *
 * @param account the account
 * @param token the token, in clear, for the only time it is readable
 */
@Serializable

data class IssuedServiceAccount (

    /* the account */
    @SerialName(value = "account") @Required val account: ServiceAccountView,

    /* the token, in clear, for the only time it is readable */
    @SerialName(value = "token") @Required val token: kotlin.String

) {


}

