/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models

import de.greluc.homeinv.client.models.InvitationView

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A freshly issued invitation, with the one copy of its token.
 *
 * @param invitation the invitation
 * @param token the secret the invited person presents. Returned exactly once. Where `plugin-smtp` is installed it also goes out by mail; where it is not, this is the only way the link reaches anybody, which 04 §4.3 describes as the expected reduced state
 */
@Serializable

data class IssuedInvitation (

    /* the invitation */
    @SerialName(value = "invitation") @Required val invitation: InvitationView,

    /* the secret the invited person presents. Returned exactly once. Where `plugin-smtp` is installed it also goes out by mail; where it is not, this is the only way the link reaches anybody, which 04 §4.3 describes as the expected reduced state */
    @SerialName(value = "token") @Required val token: kotlin.String

) {


}

