/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models

import de.greluc.homeinv.client.models.Valuation

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * What other blocks and the REST layer are allowed to see of an item.  This is the published type of the `inventory` block (REQ-NFR-023). The entity stays inside: handed out, it carries its persistence context with it, so a caller could modify the aggregate without passing the use case that guards its invariants — and would do so by accident, because a getter returning a managed entity looks exactly like one returning data.  A record, so it is immutable without anyone having to remember to make it so.
 *
 * @param attributes the fields the item's type version declares, as JSON text. The source of truth for every attribute (ADR-0004); what a key means is the catalog's business, and a client reads the type version's schema to render it
 * @param createdAt when it was created
 * @param description free text, may be `null`
 * @param id the item's UUIDv7
 * @param itemTypeVersionId which type version the attributes below were written against (REQ-CORE-002). **Without it a client cannot render them**: what an attribute key means is the catalogue's business, and reading the schema needs its id. It was absent from this view until 2026-09-21, while the very next line told a client to go and read that schema — one of the two sentences had to be wrong, and the code was
 * @param kind `PHYSICAL` or `DIGITAL`, as a string so consumers need no enum of ours
 * @param lifecycleState where the item is in its life, as an {@link ItemState ItemState} name — `ACTIVE`, `LENT`, `ARCHIVED`, `TRASHED`, `SOLD` or `DISPOSED` (04 §4.4). *Said \"stage 0 always ACTIVE\" until 2026-09-20, by which time trashing, lending and disposal all moved it*
 * @param locationId where it is; `null` for a digital item
 * @param maintenanceIntervalDays how often it needs servicing, in days, or `null` when nothing reminds about it (REQ-LIFE-004)
 * @param minimumStock the level below which this consumable needs restocking, or `null`
 * @param name the name
 * @param notes the paragraph a person wrote, in limited Markdown with the HTML already removed
 * @param quantity how many
 * @param quantityUnit the unit, may be `null`
 * @param updatedAt when it last changed
 * @param valuation 
 * @param version the optimistic lock, which a client echoes back on update to detect a concurrent edit rather than overwriting one
 */
@Serializable

data class ItemView (

    /* the fields the item's type version declares, as JSON text. The source of truth for every attribute (ADR-0004); what a key means is the catalog's business, and a client reads the type version's schema to render it */
    @SerialName(value = "attributes") @Required val attributes: kotlin.String,

    /* when it was created */
    @SerialName(value = "createdAt") @Required val createdAt: kotlin.time.Instant,

    /* free text, may be `null` */
    @SerialName(value = "description") @Required val description: kotlin.String,

    /* the item's UUIDv7 */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* which type version the attributes below were written against (REQ-CORE-002). **Without it a client cannot render them**: what an attribute key means is the catalogue's business, and reading the schema needs its id. It was absent from this view until 2026-09-21, while the very next line told a client to go and read that schema — one of the two sentences had to be wrong, and the code was */
    @SerialName(value = "itemTypeVersionId") @Required val itemTypeVersionId: kotlin.String,

    /* `PHYSICAL` or `DIGITAL`, as a string so consumers need no enum of ours */
    @SerialName(value = "kind") @Required val kind: kotlin.String,

    /* where the item is in its life, as an {@link ItemState ItemState} name — `ACTIVE`, `LENT`, `ARCHIVED`, `TRASHED`, `SOLD` or `DISPOSED` (04 §4.4). *Said \"stage 0 always ACTIVE\" until 2026-09-20, by which time trashing, lending and disposal all moved it* */
    @SerialName(value = "lifecycleState") @Required val lifecycleState: kotlin.String,

    /* where it is; `null` for a digital item */
    @SerialName(value = "locationId") @Required val locationId: kotlin.String,

    /* how often it needs servicing, in days, or `null` when nothing reminds about it (REQ-LIFE-004) */
    @SerialName(value = "maintenanceIntervalDays") @Required val maintenanceIntervalDays: kotlin.Int,

    /* the level below which this consumable needs restocking, or `null` */
    @SerialName(value = "minimumStock") @Required val minimumStock: kotlin.Double,

    /* the name */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* the paragraph a person wrote, in limited Markdown with the HTML already removed */
    @SerialName(value = "notes") @Required val notes: kotlin.String,

    /* how many */
    @SerialName(value = "quantity") @Required val quantity: kotlin.Double,

    /* the unit, may be `null` */
    @SerialName(value = "quantityUnit") @Required val quantityUnit: kotlin.String,

    /* when it last changed */
    @SerialName(value = "updatedAt") @Required val updatedAt: kotlin.time.Instant,

    @SerialName(value = "valuation") @Required val valuation: Valuation,

    /* the optimistic lock, which a client echoes back on update to detect a concurrent edit rather than overwriting one */
    @SerialName(value = "version") @Required val version: kotlin.Long

) {


}

