/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * An item type as an administrator sees it.
 *
 * @param archived whether it is offered for nothing new
 * @param builtin whether it is the one every tenant is provisioned with
 * @param draftVersionId the version being edited, or `null` when none is
 * @param icon the icon name, or `null`
 * @param id the type
 * @param key its stable key
 * @param kind whether its items exist physically
 * @param parentId the type it inherits from, or `null`
 * @param publishedVersionId the newest published version, or `null` when none is published
 * @param usefulLifeMonths 
 */
@Serializable

data class ItemTypeView (

    /* whether it is offered for nothing new */
    @SerialName(value = "archived") @Required val archived: kotlin.Boolean,

    /* whether it is the one every tenant is provisioned with */
    @SerialName(value = "builtin") @Required val builtin: kotlin.Boolean,

    /* the version being edited, or `null` when none is */
    @SerialName(value = "draftVersionId") @Required val draftVersionId: kotlin.String?,

    /* the icon name, or `null` */
    @SerialName(value = "icon") @Required val icon: kotlin.String?,

    /* the type */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* its stable key */
    @SerialName(value = "key") @Required val key: kotlin.String,

    /* whether its items exist physically */
    @SerialName(value = "kind") @Required val kind: ItemTypeView.Kind,

    /* the type it inherits from, or `null` */
    @SerialName(value = "parentId") @Required val parentId: kotlin.String?,

    /* the newest published version, or `null` when none is published */
    @SerialName(value = "publishedVersionId") @Required val publishedVersionId: kotlin.String?,

    @SerialName(value = "usefulLifeMonths") @Required val usefulLifeMonths: kotlin.Int

) {

    /**
     * whether its items exist physically
     *
     * Values: PHYSICAL,DIGITAL
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "PHYSICAL") PHYSICAL("PHYSICAL"),
        @SerialName(value = "DIGITAL") DIGITAL("DIGITAL");
        override fun toString(): kotlin.String = value
    }

}

