/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models

import de.greluc.homeinv.client.models.Evidence
import de.greluc.homeinv.client.models.MoneyJson

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * One thing.
 *
 * @param asOf the day that figure was true, which is what makes it worth anything to a reader
 * @param itemId the item
 * @param name what it is called
 * @param photo the primary photograph, or null when it has none
 * @param quantity how many, because two of a thing cost twice as much to replace
 * @param receipts every attachment the tenant marked as a receipt or a warranty proof
 * @param replacement what replacing it would cost
 * @param source who said so — `MANUAL` or `PLUGIN`
 */
@Serializable

data class Line (

    /* the day that figure was true, which is what makes it worth anything to a reader */
    @SerialName(value = "asOf") @Required val asOf: kotlinx.datetime.LocalDate,

    /* the item */
    @SerialName(value = "itemId") @Required val itemId: kotlin.String,

    /* what it is called */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* the primary photograph, or null when it has none */
    @SerialName(value = "photo") @Required val photo: Evidence,

    /* how many, because two of a thing cost twice as much to replace */
    @SerialName(value = "quantity") @Required val quantity: kotlin.Double,

    /* every attachment the tenant marked as a receipt or a warranty proof */
    @SerialName(value = "receipts") @Required val receipts: kotlin.collections.List<Evidence>,

    /* what replacing it would cost */
    @SerialName(value = "replacement") @Required val replacement: MoneyJson,

    /* who said so — `MANUAL` or `PLUGIN` */
    @SerialName(value = "source") @Required val source: kotlin.String

) {


}

