/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * One linked identity, as the account page shows it.
 *
 * @param email the address at linking, or null
 * @param id the link, for unlinking
 * @param issuer the provider that said so
 * @param lastUsedAt when it last signed somebody in, or null
 * @param linkedAt when it was made, ISO-8601
 * @param providerKey which configuration it was made through
 */
@Serializable

data class LinkView (

    /* the address at linking, or null */
    @SerialName(value = "email") @Required val email: kotlin.String,

    /* the link, for unlinking */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* the provider that said so */
    @SerialName(value = "issuer") @Required val issuer: kotlin.String,

    /* when it last signed somebody in, or null */
    @SerialName(value = "lastUsedAt") @Required val lastUsedAt: kotlin.String,

    /* when it was made, ISO-8601 */
    @SerialName(value = "linkedAt") @Required val linkedAt: kotlin.String,

    /* which configuration it was made through */
    @SerialName(value = "providerKey") @Required val providerKey: kotlin.String

) {


}

