/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * One loan, open or closed.
 *
 * @param borrowerName the name that was typed, or `null`
 * @param borrowerUserId the member who has it, or `null`
 * @param dueOn when it is due back, or `null`
 * @param handedOutOn when it went out
 * @param id the loan
 * @param itemId what was lent
 * @param note anything else worth knowing, or `null`
 * @param `open` Whether the item is still out.
 * @param recordedAt when the handover was written down
 * @param recordedBy who wrote it down
 * @param returnedOn when it came back, or `null` while it is still out
 */
@Serializable

data class LoanView (

    /* the name that was typed, or `null` */
    @SerialName(value = "borrowerName") @Required val borrowerName: kotlin.String,

    /* the member who has it, or `null` */
    @SerialName(value = "borrowerUserId") @Required val borrowerUserId: kotlin.String,

    /* when it is due back, or `null` */
    @SerialName(value = "dueOn") @Required val dueOn: kotlinx.datetime.LocalDate,

    /* when it went out */
    @SerialName(value = "handedOutOn") @Required val handedOutOn: kotlinx.datetime.LocalDate,

    /* the loan */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* what was lent */
    @SerialName(value = "itemId") @Required val itemId: kotlin.String,

    /* anything else worth knowing, or `null` */
    @SerialName(value = "note") @Required val note: kotlin.String,

    /* Whether the item is still out. */
    @SerialName(value = "open") @Required val `open`: kotlin.Boolean,

    /* when the handover was written down */
    @SerialName(value = "recordedAt") @Required val recordedAt: kotlin.time.Instant,

    /* who wrote it down */
    @SerialName(value = "recordedBy") @Required val recordedBy: kotlin.String,

    /* when it came back, or `null` while it is still out */
    @SerialName(value = "returnedOn") @Required val returnedOn: kotlinx.datetime.LocalDate

) {


}

