/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The body of a handover (REQ-LIFE-005).  Exactly one of the two borrower fields is given, which the service leaves to the database's `num_nonnulls(...) = 1` rather than restating: two places deciding one rule is how they come to disagree.
 *
 * @param handedOutOn when it went out
 * @param borrowerName who has it, in the lender's own words, or absent. Most things are lent to people with no account here
 * @param borrowerUserId a member of this tenant, or absent
 * @param dueOn when it is due back, or absent when nothing was agreed
 * @param note anything else worth knowing, or absent
 */
@Serializable

data class LoanRequest (

    /* when it went out */
    @SerialName(value = "handedOutOn") @Required val handedOutOn: kotlinx.datetime.LocalDate,

    /* who has it, in the lender's own words, or absent. Most things are lent to people with no account here */
    @SerialName(value = "borrowerName") val borrowerName: kotlin.String? = null,

    /* a member of this tenant, or absent */
    @SerialName(value = "borrowerUserId") val borrowerUserId: kotlin.String? = null,

    /* when it is due back, or absent when nothing was agreed */
    @SerialName(value = "dueOn") val dueOn: kotlinx.datetime.LocalDate? = null,

    /* anything else worth knowing, or absent */
    @SerialName(value = "note") val note: kotlin.String? = null

) {


}

