/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A kind of place a location can be: a room, a shelf, a box.  ## Why the key and not a label  The categories of stage 0 are shipped, not configured — twelve fixed keys, the same for every tenant. Their names are *interface text*, so they belong in the client's resource bundle with everything else a user reads, and REQ-NFR-032 forbids display text anywhere else. A label returned from here would be one the server would have to translate, in a language the server does not know the user prefers.  That changed at stage 1, and the labels are here now. A category nobody shipped has no key in any bundle, so it has to carry its own name; a shipped one may have been renamed by its tenant (REQ-CORE-042, \"all present and editable\"), and that name has to win over the translation.  So the rule for a client is one sentence: **use the label for the reader's language when there is one, and translate the key when there is not.** Nothing here is display text the server invented — every label in this map was typed by somebody in the tenant, which is what keeps REQ-NFR-032 true.
 *
 * @param icon an icon name for the client, or `null`
 * @param id the category, which is what a location references
 * @param key the shipped key — `room`, `shelf`, `box` — which a client translates when the tenant has given the category no name of its own
 * @param labels the tenant's own name per language tag, empty when it has none
 * @param mobile whether locations of this category travel with their contents. Every shipped one is stationary; the flag marks the relocation case a client offers, not a restriction on moving
 */
@Serializable

data class LocationCategoryView (

    /* an icon name for the client, or `null` */
    @SerialName(value = "icon") @Required val icon: kotlin.String,

    /* the category, which is what a location references */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* the shipped key — `room`, `shelf`, `box` — which a client translates when the tenant has given the category no name of its own */
    @SerialName(value = "key") @Required val key: kotlin.String,

    /* the tenant's own name per language tag, empty when it has none */
    @SerialName(value = "labels") @Required val labels: kotlin.collections.Map<kotlin.String, kotlin.String>,

    /* whether locations of this category travel with their contents. Every shipped one is stationary; the flag marks the relocation case a client offers, not a restriction on moving */
    @SerialName(value = "mobile") @Required val mobile: kotlin.Boolean

) {


}

