/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * What other blocks and the REST layer see of a location.  `ancestors` is the readable form of the materialised path: the names from the root down to this location, assembled from the rows the path names. The path itself is made of ids and is deliberately not published - it is an index structure, and publishing it would invite a client to parse it.
 *
 * @param ancestors the names from the root down to and including this location (REQ-CORE-044)
 * @param attributes the fields the category version declares, as JSON text (REQ-CORE-041)
 * @param categoryId the category
 * @param depth distance from the root
 * @param id the location
 * @param name the name
 * @param parentId the parent, or `null` for a root
 * @param version 
 */
@Serializable

data class LocationView (

    /* the names from the root down to and including this location (REQ-CORE-044) */
    @SerialName(value = "ancestors") @Required val ancestors: kotlin.collections.List<kotlin.String>,

    /* the fields the category version declares, as JSON text (REQ-CORE-041) */
    @SerialName(value = "attributes") @Required val attributes: kotlin.String,

    /* the category */
    @SerialName(value = "categoryId") @Required val categoryId: kotlin.String,

    /* distance from the root */
    @SerialName(value = "depth") @Required val depth: kotlin.Int,

    /* the location */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* the name */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* the parent, or `null` for a root */
    @SerialName(value = "parentId") @Required val parentId: kotlin.String,

    @SerialName(value = "version") @Required val version: kotlin.Long

) {


}

