/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models

import de.greluc.homeinv.client.models.MoneyJson

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The body of a maintenance entry (REQ-LIFE-003).
 *
 * @param kind what kind of work, in the tenant's own words
 * @param performedOn when the work was done
 * @param cost what it cost, or absent. Absent rather than zero for work under warranty: the two are different claims
 * @param note anything else worth knowing, or absent
 */
@Serializable

data class MaintenanceRequest (

    /* what kind of work, in the tenant's own words */
    @SerialName(value = "kind") @Required val kind: kotlin.String,

    /* when the work was done */
    @SerialName(value = "performedOn") @Required val performedOn: kotlinx.datetime.LocalDate,

    /* what it cost, or absent. Absent rather than zero for work under warranty: the two are different claims */
    @SerialName(value = "cost") val cost: MoneyJson? = null,

    /* anything else worth knowing, or absent */
    @SerialName(value = "note") val note: kotlin.String? = null

) {


}

