/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * What a CSV's columns mean (REQ-PORT-001, REQ-PORT-002).  ## Data, not a language  A profile is a set of pairs: this column is that field. Nothing in it is an expression, a formula or a condition, and that is a rule rather than an omission — ADR-0020 says the configuration surface must not become a programming language, and a mapping with an `if` in it is the first step of exactly that. A file that needs more than pairs needs editing before it is uploaded, or a plugin.  ## Two ship with the product  Homebox and InvenTree (REQ-PORT-002), as constants rather than as rows: they are the same on every instance and in every tenant, so a row per tenant would be provisioning writing the same thing over and over, and a built-in nobody may edit is what a constant already is. A tenant needing one of them changed copies it into a profile of its own.
 *
 * @param columns the mapping, from the CSV's own header to a target. A header the map does not name is reported and not written; the report lists them once, because a column nobody mapped is usually a column somebody meant to
 * @param defaultCurrency the currency every price in the file is in. A CSV rarely says, and guessing per row is how a household ends up owning things in three currencies
 * @param itemTypeKey which item type the rows are written against, or null for the tenant's built-in `general`
 * @param key how the profile is named in a request — `homebox`, `inventree`
 * @param name what it is called in a list
 * @param source the system a file comes from, recorded as the provenance of every item it creates (REQ-PORT-008)
 */
@Serializable

data class MappingProfile (

    /* the mapping, from the CSV's own header to a target. A header the map does not name is reported and not written; the report lists them once, because a column nobody mapped is usually a column somebody meant to */
    @SerialName(value = "columns") @Required val columns: kotlin.collections.Map<kotlin.String, kotlin.String>,

    /* the currency every price in the file is in. A CSV rarely says, and guessing per row is how a household ends up owning things in three currencies */
    @SerialName(value = "defaultCurrency") @Required val defaultCurrency: kotlin.String,

    /* which item type the rows are written against, or null for the tenant's built-in `general` */
    @SerialName(value = "itemTypeKey") @Required val itemTypeKey: kotlin.String,

    /* how the profile is named in a request — `homebox`, `inventree` */
    @SerialName(value = "key") @Required val key: kotlin.String,

    /* what it is called in a list */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* the system a file comes from, recorded as the provenance of every item it creates (REQ-PORT-008) */
    @SerialName(value = "source") @Required val source: kotlin.String

) {


}

