/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * What a client learns about a stored file.  Deliberately no bytes and no unsigned path. `urls` carries signed, short-lived links per variant and nothing else (REQ-MED-010); a field with a raw path would be a field that bypasses the signature, the expiry and the dedicated hostname at once.  When the scan has not finished, `urls` is empty rather than absent. A client showing a placeholder needs to know the upload exists and is not yet retrievable, which is a different state from \"no such file\" (REQ-MED-013).
 *
 * @param byteSize the size of the original
 * @param heightPx the height for an image, or `null`
 * @param id the media object
 * @param mediaType the detected type, never the declared one
 * @param primaryImage whether this is the image lists show for the thing it hangs on (REQ-MED-002). Carried per attachment rather than implied by position, because the list is paged and the primary is not guaranteed to be on the page a client is looking at
 * @param role what the attachment is for — `PHOTO`, `RECEIPT`, ` WARRANTY_PROOF` or `OTHER` (REQ-LIFE-016). On the **attachment** rather than on the file, because the same scan of a receipt may be the purchase proof of one item and an ordinary document on another, and the file is stored once by content address either way
 * @param scanState where the scan stands; only `CLEAN` yields URLs
 * @param urls variant name to signed URL, empty until the scan says clean
 * @param widthPx the width for an image, or `null`
 */
@Serializable

data class MediaView (

    /* the size of the original */
    @SerialName(value = "byteSize") @Required val byteSize: kotlin.Long,

    /* the height for an image, or `null` */
    @SerialName(value = "heightPx") @Required val heightPx: kotlin.Int?,

    /* the media object */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* the detected type, never the declared one */
    @SerialName(value = "mediaType") @Required val mediaType: kotlin.String,

    /* whether this is the image lists show for the thing it hangs on (REQ-MED-002). Carried per attachment rather than implied by position, because the list is paged and the primary is not guaranteed to be on the page a client is looking at */
    @SerialName(value = "primaryImage") @Required val primaryImage: kotlin.Boolean,

    /* what the attachment is for — `PHOTO`, `RECEIPT`, ` WARRANTY_PROOF` or `OTHER` (REQ-LIFE-016). On the **attachment** rather than on the file, because the same scan of a receipt may be the purchase proof of one item and an ordinary document on another, and the file is stored once by content address either way */
    @SerialName(value = "role") @Required val role: kotlin.String,

    /* where the scan stands; only `CLEAN` yields URLs */
    @SerialName(value = "scanState") @Required val scanState: kotlin.String,

    /* variant name to signed URL, empty until the scan says clean */
    @SerialName(value = "urls") @Required val urls: kotlin.collections.Map<kotlin.String, kotlin.String>,

    /* the width for an image, or `null` */
    @SerialName(value = "widthPx") @Required val widthPx: kotlin.Int?

) {


}

