/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A member of the tenant.
 *
 * @param displayName what the interface calls them
 * @param email the address they sign in with
 * @param joinedAt when the membership was written
 * @param role the built-in role they hold here
 * @param roleDefinitionId the tenant-owned role extending it (REQ-TEN-006), or null
 * @param roleName what to call the role: the tenant-owned role's name where there is one, otherwise the built-in name. A member list shows this rather than making a client join
 * @param scopeLocationId the part of the tree they are confined to (REQ-TEN-007), or null for the whole tenant
 * @param userId the account
 */
@Serializable

data class MemberView (

    /* what the interface calls them */
    @SerialName(value = "displayName") @Required val displayName: kotlin.String,

    /* the address they sign in with */
    @SerialName(value = "email") @Required val email: kotlin.String,

    /* when the membership was written */
    @SerialName(value = "joinedAt") @Required val joinedAt: kotlin.time.Instant,

    /* the built-in role they hold here */
    @SerialName(value = "role") @Required val role: kotlin.String,

    /* the tenant-owned role extending it (REQ-TEN-006), or null */
    @SerialName(value = "roleDefinitionId") @Required val roleDefinitionId: kotlin.String?,

    /* what to call the role: the tenant-owned role's name where there is one, otherwise the built-in name. A member list shows this rather than making a client join */
    @SerialName(value = "roleName") @Required val roleName: kotlin.String,

    /* the part of the tree they are confined to (REQ-TEN-007), or null for the whole tenant */
    @SerialName(value = "scopeLocationId") @Required val scopeLocationId: kotlin.String?,

    /* the account */
    @SerialName(value = "userId") @Required val userId: kotlin.String

) {


}

