/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Where a location is to be moved.
 *
 * @param parentId the new parent, or null to make it a root. A client that means \"out of everything\" says so with null rather than with an absent field, and both are read the same way
 */
@Serializable

data class MoveLocationRequest (

    /* the new parent, or null to make it a root. A client that means \"out of everything\" says so with null rather than with an absent field, and both are read the same way */
    @SerialName(value = "parentId") val parentId: kotlin.String? = null

) {


}

