/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * One open session, as its owner sees it.
 *
 * @param current whether this is the session making the request, which a client shows differently and should not offer to end by accident
 * @param device what the client called itself, shortened. A user agent and nothing more: it is what distinguishes \"my phone\" from \"the machine at work\" for somebody deciding which to end
 * @param handle what to call it when ending it — never the session id itself
 * @param lastSeenAt when it last made a request
 * @param origin where it signed in from, with the host part of the address removed — `203.0.113.0/24` rather than the address itself (`REQ-PRIV-006`). Enough to tell a familiar network from a strange one, not enough to be a location history
 * @param signedInAt when the session was established
 */
@Serializable

data class OpenSession (

    /* whether this is the session making the request, which a client shows differently and should not offer to end by accident */
    @SerialName(value = "current") @Required val current: kotlin.Boolean,

    /* what the client called itself, shortened. A user agent and nothing more: it is what distinguishes \"my phone\" from \"the machine at work\" for somebody deciding which to end */
    @SerialName(value = "device") @Required val device: kotlin.String,

    /* what to call it when ending it — never the session id itself */
    @SerialName(value = "handle") @Required val handle: kotlin.String,

    /* when it last made a request */
    @SerialName(value = "lastSeenAt") @Required val lastSeenAt: kotlin.time.Instant,

    /* where it signed in from, with the host part of the address removed — `203.0.113.0/24` rather than the address itself (`REQ-PRIV-006`). Enough to tell a familiar network from a strange one, not enough to be a location history */
    @SerialName(value = "origin") @Required val origin: kotlin.String,

    /* when the session was established */
    @SerialName(value = "signedInAt") @Required val signedInAt: kotlin.time.Instant

) {


}

