/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Where the rest of the collection is.
 *
 * @param estimatedTotal how many rows the whole collection holds, or `null` when nobody counted. Explicitly an estimate — an exact total over a million rows costs more than it is worth (08 §8.2) — and absent rather than wrong where counting is not cheap
 * @param hasMore whether a following page exists. Derived from the cursor rather than passed, so the two cannot disagree
 * @param nextCursor an opaque, signed cursor for the following page, or `null` when this was the last. Never an offset: offsets skip and duplicate rows on data that changes under them
 */
@Serializable

data class PageInfo (

    /* how many rows the whole collection holds, or `null` when nobody counted. Explicitly an estimate — an exact total over a million rows costs more than it is worth (08 §8.2) — and absent rather than wrong where counting is not cheap */
    @SerialName(value = "estimatedTotal") @Required val estimatedTotal: kotlin.Long?,

    /* whether a following page exists. Derived from the cursor rather than passed, so the two cannot disagree */
    @SerialName(value = "hasMore") @Required val hasMore: kotlin.Boolean,

    /* an opaque, signed cursor for the following page, or `null` when this was the last. Never an offset: offsets skip and duplicate rows on data that changes under them */
    @SerialName(value = "nextCursor") @Required val nextCursor: kotlin.String?

) {


}

