/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * What finishes a passkey registration.
 *
 * @param credential what `navigator.credentials.create()` produced, as JSON
 * @param label what to call this authenticator, or null
 */
@Serializable

data class PasskeyRegistrationRequest (

    /* what `navigator.credentials.create()` produced, as JSON */
    @SerialName(value = "credential") @Required val credential: kotlin.String,

    /* what to call this authenticator, or null */
    @SerialName(value = "label") val label: kotlin.String? = null

) {


}

