/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Where a plugin stands.
 *
 * @param disabled whether it is out of service
 * @param pluginId which plugin
 */
@Serializable

data class PluginStateView (

    /* whether it is out of service */
    @SerialName(value = "disabled") @Required val disabled: kotlin.Boolean,

    /* which plugin */
    @SerialName(value = "pluginId") @Required val pluginId: kotlin.String

) {


}

