/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * An error, as RFC 9457 describes one. A client branches on `type` and never on `detail`: the URI is stable and documented under `api/problems/`, the prose is not and is translated (REQ-API-003).
 *
 * @param detail What happened this time, in a sentence. Not stable; do not branch on it.
 * @param instance The path of the request that failed.
 * @param status The HTTP status, repeated in the body.
 * @param title The condition stable, human-readable name.
 * @param traceId The identifier of this request in the server log. Quoting it in a report leads straight to the operation (REQ-NFR-042).
 * @param type What went wrong, as an identifier. One of the tokens in `docs/reference/problem-types.yaml`, under `https://home-inv.example/problems/`. Fixed for the product rather than derived from a deployment hostname, so a client recognises it from every instance.
 */
@Serializable

data class Problem (

    /* What happened this time, in a sentence. Not stable; do not branch on it. */
    @SerialName(value = "detail") @Required val detail: kotlin.String,

    /* The path of the request that failed. */
    @SerialName(value = "instance") @Required val instance: kotlin.String,

    /* The HTTP status, repeated in the body. */
    @SerialName(value = "status") @Required val status: kotlin.Int,

    /* The condition stable, human-readable name. */
    @SerialName(value = "title") @Required val title: kotlin.String,

    /* The identifier of this request in the server log. Quoting it in a report leads straight to the operation (REQ-NFR-042). */
    @SerialName(value = "traceId") @Required val traceId: kotlin.String,

    /* What went wrong, as an identifier. One of the tokens in `docs/reference/problem-types.yaml`, under `https://home-inv.example/problems/`. Fixed for the product rather than derived from a deployment hostname, so a client recognises it from every instance. */
    @SerialName(value = "type") @Required val type: kotlin.String

) {


}

