/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A provider as the sign-in page shows it.
 *
 * @param displayName what the button says
 * @param providerKey the stable key the `begin` call names
 */
@Serializable

data class Provider (

    /* what the button says */
    @SerialName(value = "displayName") @Required val displayName: kotlin.String,

    /* the stable key the `begin` call names */
    @SerialName(value = "providerKey") @Required val providerKey: kotlin.String

) {


}

