/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A notification waiting to be delivered.
 *
 * @param address where
 * @param attempts how many tries have been made
 * @param channelKey which channel it is going out on
 * @param id its id
 * @param nextAttemptAt when the next one is due, or `null` once it is finished
 * @param state `QUEUED`, `DELIVERED` or `DEAD_LETTERED`
 */
@Serializable

data class QueuedNotification (

    /* where */
    @SerialName(value = "address") @Required val address: kotlin.String,

    /* how many tries have been made */
    @SerialName(value = "attempts") @Required val attempts: kotlin.Int,

    /* which channel it is going out on */
    @SerialName(value = "channelKey") @Required val channelKey: kotlin.String,

    /* its id */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* when the next one is due, or `null` once it is finished */
    @SerialName(value = "nextAttemptAt") @Required val nextAttemptAt: kotlin.time.Instant,

    /* `QUEUED`, `DELIVERED` or `DEAD_LETTERED` */
    @SerialName(value = "state") @Required val state: kotlin.String

) {


}

