/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The body of a relation.  *Its Javadoc sat above `MaintenanceRequest` rather than above this record until 2026-09-16, so this one had none and that one had two.*
 *
 * @param targetId the item this one points at
 * @param type `ACCESSORY_OF`, `PART_OF`, `REPLACEMENT_FOR` or `RELATED`
 */
@Serializable

data class RelationRequest (

    /* the item this one points at */
    @SerialName(value = "targetId") @Required val targetId: kotlin.String,

    /* `ACCESSORY_OF`, `PART_OF`, `REPLACEMENT_FOR` or `RELATED` */
    @SerialName(value = "type") @Required val type: kotlin.String

) {


}

