/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A stored rule.
 *
 * @param channelKey which channel
 * @param enabled whether it fires
 * @param id its id
 * @param name what a person calls it
 * @param offsetDays days relative to the trigger's date
 * @param savedSearchId which things it watches, or `null` for all of them
 * @param trigger which date or condition it watches
 * @param updatedAt when it last changed
 * @param version for `If-Match`
 */
@Serializable

data class ReminderRuleView (

    /* which channel */
    @SerialName(value = "channelKey") @Required val channelKey: kotlin.String,

    /* whether it fires */
    @SerialName(value = "enabled") @Required val enabled: kotlin.Boolean,

    /* its id */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* what a person calls it */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* days relative to the trigger's date */
    @SerialName(value = "offsetDays") @Required val offsetDays: kotlin.Int,

    /* which things it watches, or `null` for all of them */
    @SerialName(value = "savedSearchId") @Required val savedSearchId: kotlin.String?,

    /* which date or condition it watches */
    @SerialName(value = "trigger") @Required val trigger: ReminderRuleView.Trigger,

    /* when it last changed */
    @SerialName(value = "updatedAt") @Required val updatedAt: kotlin.time.Instant,

    /* for `If-Match` */
    @SerialName(value = "version") @Required val version: kotlin.Long

) {

    /**
     * which date or condition it watches
     *
     * Values: WARRANTY_EXPIRY,MAINTENANCE_DUE,LOAN_DUE,MINIMUM_STOCK,LICENCE_EXPIRY,STOCKTAKE_DISCREPANCY
     */
    @Serializable
    enum class Trigger(val value: kotlin.String) {
        @SerialName(value = "WARRANTY_EXPIRY") WARRANTY_EXPIRY("WARRANTY_EXPIRY"),
        @SerialName(value = "MAINTENANCE_DUE") MAINTENANCE_DUE("MAINTENANCE_DUE"),
        @SerialName(value = "LOAN_DUE") LOAN_DUE("LOAN_DUE"),
        @SerialName(value = "MINIMUM_STOCK") MINIMUM_STOCK("MINIMUM_STOCK"),
        @SerialName(value = "LICENCE_EXPIRY") LICENCE_EXPIRY("LICENCE_EXPIRY"),
        @SerialName(value = "STOCKTAKE_DISCREPANCY") STOCKTAKE_DISCREPANCY("STOCKTAKE_DISCREPANCY");
        override fun toString(): kotlin.String = value
    }

}

