/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models

import de.greluc.homeinv.client.models.MoneyJson
import de.greluc.homeinv.client.models.Room

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * One report.
 *
 * @param converted always `false`, and present rather than implied: `REQ-LIFE-017` asks the report to **state** that no conversion took place, and a field a client can render is a statement where a missing field is an assumption
 * @param producedOn the day it was made, which belongs on a document somebody files
 * @param rooms one per place holding anything, deepest path first so a reader walks the house in order
 * @param totals the whole report's replacement value, per currency
 * @param withoutAReplacementValue how many items were left out because nobody has recorded what replacing them would cost. Counted rather than hidden: an insurance report that quietly omits half a household is worse than one that says it did
 */
@Serializable

data class Report (

    /* always `false`, and present rather than implied: `REQ-LIFE-017` asks the report to **state** that no conversion took place, and a field a client can render is a statement where a missing field is an assumption */
    @SerialName(value = "converted") @Required val converted: kotlin.Boolean,

    /* the day it was made, which belongs on a document somebody files */
    @SerialName(value = "producedOn") @Required val producedOn: kotlinx.datetime.LocalDate,

    /* one per place holding anything, deepest path first so a reader walks the house in order */
    @SerialName(value = "rooms") @Required val rooms: kotlin.collections.List<Room>,

    /* the whole report's replacement value, per currency */
    @SerialName(value = "totals") @Required val totals: kotlin.collections.List<MoneyJson>,

    /* how many items were left out because nobody has recorded what replacing them would cost. Counted rather than hidden: an insurance report that quietly omits half a household is worse than one that says it did */
    @SerialName(value = "withoutAReplacementValue") @Required val withoutAReplacementValue: kotlin.Long

) {


}

