/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The tenant that is answering again.
 *
 * @param id the tenant
 * @param state its state, which is `ACTIVE` by the time this is returned
 */
@Serializable

data class RevokedView (

    /* the tenant */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* its state, which is `ACTIVE` by the time this is returned */
    @SerialName(value = "state") @Required val state: kotlin.String

) {


}

