/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The body of a role definition.
 *
 * @param baseRole the built-in role it extends. Ignored on an update: changing it would silently move everybody holding the role to a different floor
 * @param name what to call it
 * @param description what it is for, or omitted
 * @param permissions the permission ids it adds beyond that base
 */
@Serializable

data class RoleDefinitionRequest (

    /* the built-in role it extends. Ignored on an update: changing it would silently move everybody holding the role to a different floor */
    @SerialName(value = "baseRole") @Required val baseRole: kotlin.String,

    /* what to call it */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* what it is for, or omitted */
    @SerialName(value = "description") val description: kotlin.String? = null,

    /* the permission ids it adds beyond that base */
    @SerialName(value = "permissions") val permissions: kotlin.collections.List<kotlin.String>? = null

) {


}

