/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The body of a role change.
 *
 * @param role one of `OWNER`, `ADMIN`, `MEMBER`, `CONTRIBUTOR`, `VIEWER`, `GUEST`. A name this build does not know grants nothing and is refused
 * @param roleDefinitionId a tenant-owned role extending it (REQ-TEN-006), or omitted for a plain built-in role. Where it is given it decides the base, and `role` is ignored
 * @param scopeLocationId a location to confine them to (REQ-TEN-007), or omitted for the whole tenant
 */
@Serializable

data class RoleRequest (

    /* one of `OWNER`, `ADMIN`, `MEMBER`, `CONTRIBUTOR`, `VIEWER`, `GUEST`. A name this build does not know grants nothing and is refused */
    @SerialName(value = "role") @Required val role: kotlin.String,

    /* a tenant-owned role extending it (REQ-TEN-006), or omitted for a plain built-in role. Where it is given it decides the base, and `role` is ignored */
    @SerialName(value = "roleDefinitionId") val roleDefinitionId: kotlin.String? = null,

    /* a location to confine them to (REQ-TEN-007), or omitted for the whole tenant */
    @SerialName(value = "scopeLocationId") val scopeLocationId: kotlin.String? = null

) {


}

