/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A tenant-owned role.
 *
 * @param baseRole the built-in role it extends
 * @param description what it is for, or null
 * @param effectivePermissions everything it holds, base included — so a client can show what a role means without re-implementing the ladder
 * @param id the definition
 * @param name what the tenant calls it
 * @param permissions the ids it adds
 */
@Serializable

data class RoleView (

    /* the built-in role it extends */
    @SerialName(value = "baseRole") @Required val baseRole: kotlin.String,

    /* what it is for, or null */
    @SerialName(value = "description") @Required val description: kotlin.String?,

    /* everything it holds, base included — so a client can show what a role means without re-implementing the ladder */
    @SerialName(value = "effectivePermissions") @Required val effectivePermissions: kotlin.collections.List<kotlin.String>,

    /* the definition */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* what the tenant calls it */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* the ids it adds */
    @SerialName(value = "permissions") @Required val permissions: kotlin.collections.List<kotlin.String>

) {


}

