/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A role a rule is about.
 *
 * @param role the built-in role's name, or null
 * @param roleDefinitionId the tenant-owned role, or null
 */
@Serializable

data class RoleReference (

    /* the built-in role's name, or null */
    @SerialName(value = "role") @Required val role: kotlin.String?,

    /* the tenant-owned role, or null */
    @SerialName(value = "roleDefinitionId") @Required val roleDefinitionId: kotlin.String?

) {


}

