/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models

import de.greluc.homeinv.client.models.Line
import de.greluc.homeinv.client.models.MoneyJson

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * One place and what is in it.
 *
 * @param lines the things directly in it
 * @param locationId the place
 * @param path what to call it, as a person would say it — `House / Garage / Shelf`
 * @param totals what they would cost to replace, per currency
 */
@Serializable

data class Room (

    /* the things directly in it */
    @SerialName(value = "lines") @Required val lines: kotlin.collections.List<Line>,

    /* the place */
    @SerialName(value = "locationId") @Required val locationId: kotlin.String,

    /* what to call it, as a person would say it — `House / Garage / Shelf` */
    @SerialName(value = "path") @Required val path: kotlin.String,

    /* what they would cost to replace, per currency */
    @SerialName(value = "totals") @Required val totals: kotlin.collections.List<MoneyJson?>

) {


}

