/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The body of a reminder rule (REQ-NOTI-001).
 *
 * @param channelKey which channel, as a plugin manifest names it
 * @param name what a person calls it
 * @param trigger which date or condition it watches. Only a trigger this installation serves is accepted; `GET /triggers` says which those are
 * @param enabled whether it fires; absent means it does
 * @param offsetDays days relative to the trigger's date: **positive warns early** (14 is a fortnight before a warranty ends), **negative waits until after** (-1 fires the day after a loan was due), zero fires on the day. Stored as zero for a trigger that has no date, so the screen and the behaviour agree
 * @param savedSearchId which things to watch, or absent for everything the trigger finds
 */
@Serializable

data class RuleRequest (

    /* which channel, as a plugin manifest names it */
    @SerialName(value = "channelKey") @Required val channelKey: kotlin.String,

    /* what a person calls it */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* which date or condition it watches. Only a trigger this installation serves is accepted; `GET /triggers` says which those are */
    @SerialName(value = "trigger") @Required val trigger: RuleRequest.Trigger,

    /* whether it fires; absent means it does */
    @SerialName(value = "enabled") val enabled: kotlin.Boolean? = null,

    /* days relative to the trigger's date: **positive warns early** (14 is a fortnight before a warranty ends), **negative waits until after** (-1 fires the day after a loan was due), zero fires on the day. Stored as zero for a trigger that has no date, so the screen and the behaviour agree */
    @SerialName(value = "offsetDays") val offsetDays: kotlin.Int? = null,

    /* which things to watch, or absent for everything the trigger finds */
    @SerialName(value = "savedSearchId") val savedSearchId: kotlin.String? = null

) {

    /**
     * which date or condition it watches. Only a trigger this installation serves is accepted; `GET /triggers` says which those are
     *
     * Values: WARRANTY_EXPIRY,MAINTENANCE_DUE,LOAN_DUE,MINIMUM_STOCK,LICENCE_EXPIRY,STOCKTAKE_DISCREPANCY
     */
    @Serializable
    enum class Trigger(val value: kotlin.String) {
        @SerialName(value = "WARRANTY_EXPIRY") WARRANTY_EXPIRY("WARRANTY_EXPIRY"),
        @SerialName(value = "MAINTENANCE_DUE") MAINTENANCE_DUE("MAINTENANCE_DUE"),
        @SerialName(value = "LOAN_DUE") LOAN_DUE("LOAN_DUE"),
        @SerialName(value = "MINIMUM_STOCK") MINIMUM_STOCK("MINIMUM_STOCK"),
        @SerialName(value = "LICENCE_EXPIRY") LICENCE_EXPIRY("LICENCE_EXPIRY"),
        @SerialName(value = "STOCKTAKE_DISCREPANCY") STOCKTAKE_DISCREPANCY("STOCKTAKE_DISCREPANCY");
        override fun toString(): kotlin.String = value
    }

}

