/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A saved search as the wire spells it.  The same names a query takes: `q`, `filters`, `sort`. The port's view calls the first one `text`, which is what it is; here it is what a client typed, and a client that sends `q` and is answered `text` cannot put a saved search back into the query bar without translating it.
 *
 * @param createdAt when it was saved
 * @param filters the `filter` parameters verbatim
 * @param id its identifier
 * @param name what it is called
 * @param q the text to search for, or `null`
 * @param sort the sort key, or `null`
 * @param updatedAt when it last changed
 * @param version the optimistic-lock version, which is also its ETag
 */
@Serializable

data class SavedSearchResponse (

    /* when it was saved */
    @SerialName(value = "createdAt") @Required val createdAt: kotlin.time.Instant,

    /* the `filter` parameters verbatim */
    @SerialName(value = "filters") @Required val filters: kotlin.collections.List<kotlin.String>,

    /* its identifier */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* what it is called */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* the text to search for, or `null` */
    @SerialName(value = "q") @Required val q: kotlin.String,

    /* the sort key, or `null` */
    @SerialName(value = "sort") @Required val sort: kotlin.String,

    /* when it last changed */
    @SerialName(value = "updatedAt") @Required val updatedAt: kotlin.time.Instant,

    /* the optimistic-lock version, which is also its ETag */
    @SerialName(value = "version") @Required val version: kotlin.Long

) {


}

