/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Who the caller is, on the wire.  One record for the whole access layer, and it is here rather than nested in a controller because **two controllers return it**: signing in answers with it, and so does switching tenant. Two identical records nested in two controllers is what it was until 2026-09-21, and the problem with that is not the duplication — springdoc names a schema after the simple class name, so two types called `SessionView` publish one shape under one name and silently lose the other. They happened to be identical; the next pair need not be, and nothing would have said so (REQ-API-002, `SchemaNameTest`).
 *
 * @param email the address they logged in with
 * @param locale the language on their profile, which the interface starts in (REQ-NFR-033)
 * @param role the membership's role. Returned so the client can decide what to *offer*; it never decides what is allowed, which happens in the application layer on every request (REQ-SEC-022). A UI that shows a button nobody may press teaches people to ignore errors.
 * @param tenantId the tenant this session acts for
 * @param userId the person
 */
@Serializable

data class SessionView (

    /* the address they logged in with */
    @SerialName(value = "email") @Required val email: kotlin.String,

    /* the language on their profile, which the interface starts in (REQ-NFR-033) */
    @SerialName(value = "locale") @Required val locale: kotlin.String,

    /* the membership's role. Returned so the client can decide what to *offer*; it never decides what is allowed, which happens in the application layer on every request (REQ-SEC-022). A UI that shows a button nobody may press teaches people to ignore errors. */
    @SerialName(value = "role") @Required val role: kotlin.String,

    /* the tenant this session acts for */
    @SerialName(value = "tenantId") @Required val tenantId: kotlin.String,

    /* the person */
    @SerialName(value = "userId") @Required val userId: kotlin.String

) {


}

