/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * One setting a plugin declares, with what this tenant made of it.
 *
 * @param defaultValue what applies when nothing is set here, or null
 * @param key the manifest's key
 * @param label what a person sees, by language tag — multilingual data, like a field label
 * @param required whether the plugin says it cannot work without one
 * @param set whether a value is stored, which is all a surface learns about a secret
 * @param type `string`, `secret`, `enum`, `integer` or `boolean`
 * @param `value` what this tenant set, and **always null for a secret**
 * @param propertyValues the choices, for an `enum`; empty otherwise
 */
@Serializable

data class SettingView (

    /* what applies when nothing is set here, or null */
    @SerialName(value = "defaultValue") @Required val defaultValue: kotlin.String?,

    /* the manifest's key */
    @SerialName(value = "key") @Required val key: kotlin.String,

    /* what a person sees, by language tag — multilingual data, like a field label */
    @SerialName(value = "label") @Required val label: kotlin.collections.Map<kotlin.String, kotlin.String>,

    /* whether the plugin says it cannot work without one */
    @SerialName(value = "required") @Required val required: kotlin.Boolean,

    /* whether a value is stored, which is all a surface learns about a secret */
    @SerialName(value = "set") @Required val set: kotlin.Boolean,

    /* `string`, `secret`, `enum`, `integer` or `boolean` */
    @SerialName(value = "type") @Required val type: kotlin.String,

    /* what this tenant set, and **always null for a secret** */
    @SerialName(value = "value") @Required val `value`: kotlin.String,

    /* the choices, for an `enum`; empty otherwise */
    @SerialName(value = "values") @Required val propertyValues: kotlin.collections.List<kotlin.String>

) {


}

