/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The body of a switch.
 *
 * @param tenantId the tenant to act for. Must be one the caller is a member of; anything else is answered as though it did not exist
 */
@Serializable

data class SwitchTenantRequest (

    /* the tenant to act for. Must be one the caller is a member of; anything else is answered as though it did not exist */
    @SerialName(value = "tenantId") @Required val tenantId: kotlin.String

) {


}

