/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A group of tags — \"condition\", \"room\", \"owner\" (REQ-CORE-061).
 *
 * @param displayOrder where the group sits among the others on a form
 * @param exclusive whether a thing may carry only one tag of this group. \"Condition\" is one of new, used or broken; a thing that was both would be a thing whose condition nobody can read
 * @param id the group
 * @param key the stable key, which is what an import or an export names
 * @param labels the group's name per language tag, as the tenant wrote it. Multilingual data rather than interface text: the server cannot translate a word a tenant invented (REQ-NFR-032)
 */
@Serializable

data class TagGroupView (

    /* where the group sits among the others on a form */
    @SerialName(value = "displayOrder") @Required val displayOrder: kotlin.Int,

    /* whether a thing may carry only one tag of this group. \"Condition\" is one of new, used or broken; a thing that was both would be a thing whose condition nobody can read */
    @SerialName(value = "exclusive") @Required val exclusive: kotlin.Boolean,

    /* the group */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* the stable key, which is what an import or an export names */
    @SerialName(value = "key") @Required val key: kotlin.String,

    /* the group's name per language tag, as the tenant wrote it. Multilingual data rather than interface text: the server cannot translate a word a tenant invented (REQ-NFR-032) */
    @SerialName(value = "labels") @Required val labels: kotlin.collections.Map<kotlin.String, kotlin.String>

) {


}

