/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The body of a group creation.
 *
 * @param key the stable key
 * @param displayOrder where the group sits among the others
 * @param exclusive whether a thing may carry only one tag of this group
 * @param labels the group's name per language tag
 */
@Serializable

data class TagGroupRequest (

    /* the stable key */
    @SerialName(value = "key") @Required val key: kotlin.String,

    /* where the group sits among the others */
    @SerialName(value = "displayOrder") val displayOrder: kotlin.Int? = null,

    /* whether a thing may carry only one tag of this group */
    @SerialName(value = "exclusive") val exclusive: kotlin.Boolean? = null,

    /* the group's name per language tag */
    @SerialName(value = "labels") val labels: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {


}

