/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A tag as everything outside this block sees it.
 *
 * @param colour `#rrggbb`, or `null` when the tenant chose none (REQ-CORE-062)
 * @param groupId the group it belongs to, or `null`
 * @param icon an icon name for clients, or `null`
 * @param id the tag
 * @param mergedInto what this tag became, or `null` while it is itself. A tag with a value here is a tombstone: it is offered nowhere, carries nothing, and exists so a client holding its id is redirected rather than told the tag never existed (REQ-CORE-063)
 * @param name the name a person reads, unique per tenant among the live ones
 */
@Serializable

data class TagView (

    /* `#rrggbb`, or `null` when the tenant chose none (REQ-CORE-062) */
    @SerialName(value = "colour") @Required val colour: kotlin.String?,

    /* the group it belongs to, or `null` */
    @SerialName(value = "groupId") @Required val groupId: kotlin.String?,

    /* an icon name for clients, or `null` */
    @SerialName(value = "icon") @Required val icon: kotlin.String?,

    /* the tag */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* what this tag became, or `null` while it is itself. A tag with a value here is a tombstone: it is offered nowhere, carries nothing, and exists so a client holding its id is redirected rather than told the tag never existed (REQ-CORE-063) */
    @SerialName(value = "mergedInto") @Required val mergedInto: kotlin.String?,

    /* the name a person reads, unique per tenant among the live ones */
    @SerialName(value = "name") @Required val name: kotlin.String

) {


}

