/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The body of a webhook target (REQ-API-010).
 *
 * @param eventTypes which events it wants, by the names `GET /event-types` lists. At least one: a target that subscribes to nothing would never be delivered to
 * @param url where to post. `https` only, and checked three times over — here, by the column, and by the plugin including the address it resolves to (REQ-SEC-034)
 * @param description what a person calls it, or absent
 * @param enabled whether it receives anything; absent means it does
 * @param signingSecret what to sign with, at least 32 characters. Required when creating; on a replace, absent keeps the stored one — a form that cannot show a secret must not clear it by being saved
 */
@Serializable

data class TargetRequest (

    /* which events it wants, by the names `GET /event-types` lists. At least one: a target that subscribes to nothing would never be delivered to */
    @SerialName(value = "eventTypes") @Required val eventTypes: kotlin.collections.Set<kotlin.String>,

    /* where to post. `https` only, and checked three times over — here, by the column, and by the plugin including the address it resolves to (REQ-SEC-034) */
    @SerialName(value = "url") @Required val url: kotlin.String,

    /* what a person calls it, or absent */
    @SerialName(value = "description") val description: kotlin.String? = null,

    /* whether it receives anything; absent means it does */
    @SerialName(value = "enabled") val enabled: kotlin.Boolean? = null,

    /* what to sign with, at least 32 characters. Required when creating; on a replace, absent keeps the stored one — a form that cannot show a secret must not clear it by being saved */
    @SerialName(value = "signingSecret") val signingSecret: kotlin.String? = null

) {


}

