/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * One shipped template, as a picker shows it.
 *
 * @param fieldCount how many fields it brings, so a person can tell a starting point from a catalogue before importing one
 * @param key the template's key, which becomes the type's key on import
 * @param kind whether its items exist physically
 * @param labels its name per language tag
 */
@Serializable

data class TemplateView (

    /* how many fields it brings, so a person can tell a starting point from a catalogue before importing one */
    @SerialName(value = "fieldCount") @Required val fieldCount: kotlin.Int,

    /* the template's key, which becomes the type's key on import */
    @SerialName(value = "key") @Required val key: kotlin.String,

    /* whether its items exist physically */
    @SerialName(value = "kind") @Required val kind: TemplateView.Kind,

    /* its name per language tag */
    @SerialName(value = "labels") @Required val labels: kotlin.collections.Map<kotlin.String, kotlin.String>

) {

    /**
     * whether its items exist physically
     *
     * Values: PHYSICAL,DIGITAL
     */
    @Serializable
    enum class Kind(val value: kotlin.String) {
        @SerialName(value = "PHYSICAL") PHYSICAL("PHYSICAL"),
        @SerialName(value = "DIGITAL") DIGITAL("DIGITAL");
        override fun toString(): kotlin.String = value
    }

}

