/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models

import de.greluc.homeinv.client.models.TemplateView

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The templates this build ships.  No cursor and no page, and that is not an oversight: the set is fixed by the release, the same for every tenant, and eight entries long. A cursor here would be a cursor over a constant.
 *
 * @param templates the templates, in the order the shipped file lists them
 */
@Serializable

data class TemplateList (

    /* the templates, in the order the shipped file lists them */
    @SerialName(value = "templates") @Required val templates: kotlin.collections.List<TemplateView>

) {


}

