/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A tenant's state.
 *
 * @param id the tenant
 * @param state `ACTIVE`, `SUSPENDED` or `PENDING_DELETION`
 */
@Serializable

data class TenantStateView (

    /* the tenant */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* `ACTIVE`, `SUSPENDED` or `PENDING_DELETION` */
    @SerialName(value = "state") @Required val state: kotlin.String

) {


}

