/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A tenant as its member sees it.
 *
 * @param id the tenant
 * @param name its display name
 * @param role the role the caller holds in it
 */
@Serializable

data class TenantView (

    /* the tenant */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* its display name */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* the role the caller holds in it */
    @SerialName(value = "role") @Required val role: kotlin.String

) {


}

