/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * One file a component ships, reproduced as it is.
 *
 * @param path where the file sat inside the component, so a reader can check it
 * @param text the file, verbatim
 */
@Serializable

data class ThirdPartyNoticeView (

    /* where the file sat inside the component, so a reader can check it */
    @SerialName(value = "path") @Required val path: kotlin.String,

    /* the file, verbatim */
    @SerialName(value = "text") @Required val text: kotlin.String

) {


}

