/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models

import de.greluc.homeinv.client.models.ThirdPartyNoticeView

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * One third-party component the artifact carries.
 *
 * @param licences the SPDX identifiers it is declared under, or the names where what was declared is not an identifier
 * @param name the component's name as the artifact spells it
 * @param notices the licence and notice files the component itself ships, verbatim; empty where the licence's text is the same for every component and appears in `licences`
 * @param version its version
 */
@Serializable

data class ThirdPartyComponentView (

    /* the SPDX identifiers it is declared under, or the names where what was declared is not an identifier */
    @SerialName(value = "licences") @Required val licences: kotlin.collections.List<kotlin.String>,

    /* the component's name as the artifact spells it */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* the licence and notice files the component itself ships, verbatim; empty where the licence's text is the same for every component and appears in `licences` */
    @SerialName(value = "notices") @Required val notices: kotlin.collections.List<ThirdPartyNoticeView>,

    /* its version */
    @SerialName(value = "version") @Required val version: kotlin.String

) {


}

