/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * What a mass revocation did.  Not `RevokedView`: springdoc names a schema after the simple class name, and `TenantRevocationController` already publishes one under that name — two types with one name publish one shape and lose the other, silently, in the document every generated client is built from (`SchemaNameTest`, ADR-0080).
 *
 * @param revoked how many tokens stopped working
 */
@Serializable

data class TokensRevokedView (

    /* how many tokens stopped working */
    @SerialName(value = "revoked") @Required val revoked: kotlin.Int

) {


}

