/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A secret that has just been generated.
 *
 * @param provisioningUri the `otpauth://` URI a QR code carries
 * @param secret the shared secret in base32, for somebody typing it in by hand
 */
@Serializable

data class TotpEnrolmentView (

    /* the `otpauth://` URI a QR code carries */
    @SerialName(value = "provisioningUri") @Required val provisioningUri: kotlin.String,

    /* the shared secret in base32, for somebody typing it in by hand */
    @SerialName(value = "secret") @Required val secret: kotlin.String

) {


}

