/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * What to change about a location category.  Replaced whole, every field of it: a partial body would make removing a translation impossible, since there is no spelling for \"drop this language\" in a merge.
 *
 * @param icon an icon name for clients, or omitted
 * @param labels the name per language tag; omitted or empty leaves it nameless and a client falls back to translating the key
 * @param mobile whether its places travel with their contents
 */
@Serializable

data class UpdateCategoryRequest (

    /* an icon name for clients, or omitted */
    @SerialName(value = "icon") val icon: kotlin.String? = null,

    /* the name per language tag; omitted or empty leaves it nameless and a client falls back to translating the key */
    @SerialName(value = "labels") val labels: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* whether its places travel with their contents */
    @SerialName(value = "mobile") val mobile: kotlin.Boolean? = null

) {


}

