/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models

import de.greluc.homeinv.client.models.ValuationRequest

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The body of an update. `kind` is absent: a physical item does not become a digital one.
 *
 * @param name the new name
 * @param attributes the new attribute set as a JSON object, checked against the version the item was written against rather than against whatever the type says today
 * @param description the new description
 * @param locationId the new location; required while the item is physical
 * @param maintenanceIntervalDays how often it needs servicing, in days, or omitted when nothing should remind about it (REQ-LIFE-004). Days and not months, because \"every 3 months from 31 January\" has no answer that is not a surprise to somebody
 * @param minimumStock the new restocking level, or omitted to stop tracking one
 * @param notes the new notes; HTML is removed before they are stored
 * @param quantity the new quantity; `null` means one
 * @param quantityUnit the new unit
 * @param valuation what it cost, what covers it and what replacing it would cost, or omitted
 */
@Serializable

data class UpdateItemRequest (

    /* the new name */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* the new attribute set as a JSON object, checked against the version the item was written against rather than against whatever the type says today */
    @SerialName(value = "attributes") val attributes: kotlin.String? = null,

    /* the new description */
    @SerialName(value = "description") val description: kotlin.String? = null,

    /* the new location; required while the item is physical */
    @SerialName(value = "locationId") val locationId: kotlin.String? = null,

    /* how often it needs servicing, in days, or omitted when nothing should remind about it (REQ-LIFE-004). Days and not months, because \"every 3 months from 31 January\" has no answer that is not a surprise to somebody */
    @SerialName(value = "maintenanceIntervalDays") val maintenanceIntervalDays: kotlin.Int? = null,

    /* the new restocking level, or omitted to stop tracking one */
    @SerialName(value = "minimumStock") val minimumStock: kotlin.Double? = null,

    /* the new notes; HTML is removed before they are stored */
    @SerialName(value = "notes") val notes: kotlin.String? = null,

    /* the new quantity; `null` means one */
    @SerialName(value = "quantity") val quantity: kotlin.Double? = null,

    /* the new unit */
    @SerialName(value = "quantityUnit") val quantityUnit: kotlin.String? = null,

    /* what it cost, what covers it and what replacing it would cost, or omitted */
    @SerialName(value = "valuation") val valuation: ValuationRequest? = null

) {


}

