/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * What to change about an item type.
 *
 * @param icon the icon, or null to clear it
 * @param usefulLifeMonths how long a thing of this type is expected to last, for the straight-line depreciation of REQ-LIFE-009, or null for a type that is not depreciated. Nothing ships with one: how long a household's furniture lasts is a judgement about that household, and a figure this application invented would end up in somebody's insurance report. Clearing it takes the depreciated values with it on the next run
 */
@Serializable

data class UpdateItemTypeRequest (

    /* the icon, or null to clear it */
    @SerialName(value = "icon") val icon: kotlin.String? = null,

    /* how long a thing of this type is expected to last, for the straight-line depreciation of REQ-LIFE-009, or null for a type that is not depreciated. Nothing ships with one: how long a household's furniture lasts is a judgement about that household, and a figure this application invented would end up in somebody's insurance report. Clearing it takes the depreciated values with it on the next run */
    @SerialName(value = "usefulLifeMonths") val usefulLifeMonths: kotlin.Int? = null

) {


}

