/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * One permitted value.
 *
 * @param archived whether it is still offered for new input
 * @param displayOrder its position
 * @param id the entry
 * @param labels its readable form per language tag
 * @param `value` what is stored in an item's attributes
 */
@Serializable

data class ValueListEntryView (

    /* whether it is still offered for new input */
    @SerialName(value = "archived") @Required val archived: kotlin.Boolean,

    /* its position */
    @SerialName(value = "displayOrder") @Required val displayOrder: kotlin.Int,

    /* the entry */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* its readable form per language tag */
    @SerialName(value = "labels") @Required val labels: kotlin.collections.Map<kotlin.String, kotlin.String>,

    /* what is stored in an item's attributes */
    @SerialName(value = "value") @Required val `value`: kotlin.String

) {


}

