/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models

import de.greluc.homeinv.client.models.MoneyJson

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * What an item cost, what covers it, and what it would cost to replace (REQ-LIFE-001/002/014).  ## Three figures, never derived from one another  `REQ-LIFE-014` says it about the replacement value in as many words — \"independent of the current value and never derived from it\" — and it holds for all three. A camera bought for 900 may be worth 200 second-hand and cost 1,100 to buy new today; an insurer asks for the third number, a seller for the second and the tax office for the first. Each carries its own as-of date, because a valuation without one is a number of unknown age.  Columns on the item rather than fields of a type version, decided with the owner on 2026-09-13: `REQ-LIFE-015` asks for totals per location, type and tag across *every* type, and an attribute exists only where its type happened to declare it, under whatever name that type chose.
 *
 * @param currentValue what it is worth now, or `null` (REQ-LIFE-009)
 * @param currentValueAsOf the day that figure was true, or `null`
 * @param currentValueSource who says so — {@link Provenance#MANUAL Provenance#MANUAL}, {@link de.greluc.homeinv.inventory.api.Valuation      Provenance#DEPRECIATION} or {@link Provenance#PLUGIN Provenance#PLUGIN} — or `null`. Not decoration: the refresh run rewrites only what it wrote, so a figure somebody typed survives the night
 * @param lifetimeWarranty whether it is covered for life, in which case `warrantyUntil` is `null`. A flag rather than a date far in the future, because \"2099-12-31\" is a date somebody would eventually have to explain
 * @param purchase what it cost, or `null`
 * @param purchaseSource where from — a shop, a person, a listing — or `null`. Free text: an invoice is an attachment like any other and needs no field of its own
 * @param purchasedOn when it was bought, or `null`
 * @param replacement what it would cost to replace, or `null`
 * @param replacementAsOf the day that figure was true, or `null`
 * @param replacementSource who said so — {@link Provenance#MANUAL Provenance#MANUAL} or {@link Provenance#PLUGIN Provenance#PLUGIN} — or `null`
 * @param warrantyUntil when the warranty ends, or `null`
 */
@Serializable

data class Valuation (

    /* what it is worth now, or `null` (REQ-LIFE-009) */
    @SerialName(value = "currentValue") @Required val currentValue: MoneyJson?,

    /* the day that figure was true, or `null` */
    @SerialName(value = "currentValueAsOf") @Required val currentValueAsOf: kotlinx.datetime.LocalDate?,

    /* who says so — {@link Provenance#MANUAL Provenance#MANUAL}, {@link de.greluc.homeinv.inventory.api.Valuation      Provenance#DEPRECIATION} or {@link Provenance#PLUGIN Provenance#PLUGIN} — or `null`. Not decoration: the refresh run rewrites only what it wrote, so a figure somebody typed survives the night */
    @SerialName(value = "currentValueSource") @Required val currentValueSource: Valuation.CurrentValueSource?,

    /* whether it is covered for life, in which case `warrantyUntil` is `null`. A flag rather than a date far in the future, because \"2099-12-31\" is a date somebody would eventually have to explain */
    @SerialName(value = "lifetimeWarranty") @Required val lifetimeWarranty: kotlin.Boolean?,

    /* what it cost, or `null` */
    @SerialName(value = "purchase") @Required val purchase: MoneyJson?,

    /* where from — a shop, a person, a listing — or `null`. Free text: an invoice is an attachment like any other and needs no field of its own */
    @SerialName(value = "purchaseSource") @Required val purchaseSource: kotlin.String?,

    /* when it was bought, or `null` */
    @SerialName(value = "purchasedOn") @Required val purchasedOn: kotlinx.datetime.LocalDate?,

    /* what it would cost to replace, or `null` */
    @SerialName(value = "replacement") @Required val replacement: MoneyJson?,

    /* the day that figure was true, or `null` */
    @SerialName(value = "replacementAsOf") @Required val replacementAsOf: kotlinx.datetime.LocalDate?,

    /* who said so — {@link Provenance#MANUAL Provenance#MANUAL} or {@link Provenance#PLUGIN Provenance#PLUGIN} — or `null` */
    @SerialName(value = "replacementSource") @Required val replacementSource: Valuation.ReplacementSource?,

    /* when the warranty ends, or `null` */
    @SerialName(value = "warrantyUntil") @Required val warrantyUntil: kotlinx.datetime.LocalDate?

) {

    /**
     * who says so — {@link Provenance#MANUAL Provenance#MANUAL}, {@link de.greluc.homeinv.inventory.api.Valuation      Provenance#DEPRECIATION} or {@link Provenance#PLUGIN Provenance#PLUGIN} — or `null`. Not decoration: the refresh run rewrites only what it wrote, so a figure somebody typed survives the night
     *
     * Values: MANUAL,DEPRECIATION,PLUGIN
     */
    @Serializable
    enum class CurrentValueSource(val value: kotlin.String) {
        @SerialName(value = "MANUAL") MANUAL("MANUAL"),
        @SerialName(value = "DEPRECIATION") DEPRECIATION("DEPRECIATION"),
        @SerialName(value = "PLUGIN") PLUGIN("PLUGIN");
        override fun toString(): kotlin.String = value
    }
    /**
     * who said so — {@link Provenance#MANUAL Provenance#MANUAL} or {@link Provenance#PLUGIN Provenance#PLUGIN} — or `null`
     *
     * Values: MANUAL,DEPRECIATION,PLUGIN
     */
    @Serializable
    enum class ReplacementSource(val value: kotlin.String) {
        @SerialName(value = "MANUAL") MANUAL("MANUAL"),
        @SerialName(value = "DEPRECIATION") DEPRECIATION("DEPRECIATION"),
        @SerialName(value = "PLUGIN") PLUGIN("PLUGIN");
        override fun toString(): kotlin.String = value
    }

}

