/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models

import de.greluc.homeinv.client.models.Figures

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * One group's figures.
 *
 * @param id the location, type or tag
 * @param label what to call it, in the tenant's own words
 * @param own the totals for things directly in this group
 * @param ownCount how many things are directly in this group
 * @param subtree the totals including everything beneath it; equal to `own` where the dimension has no tree
 * @param subtreeCount how many including everything beneath it
 */
@Serializable

data class ValuationRow (

    /* the location, type or tag */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* what to call it, in the tenant's own words */
    @SerialName(value = "label") @Required val label: kotlin.String,

    /* the totals for things directly in this group */
    @SerialName(value = "own") @Required val own: Figures,

    /* how many things are directly in this group */
    @SerialName(value = "ownCount") @Required val ownCount: kotlin.Long,

    /* the totals including everything beneath it; equal to `own` where the dimension has no tree */
    @SerialName(value = "subtree") @Required val subtree: Figures,

    /* how many including everything beneath it */
    @SerialName(value = "subtreeCount") @Required val subtreeCount: kotlin.Long

) {


}

