/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models

import de.greluc.homeinv.client.models.ValuationRow

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * One report.
 *
 * @param converted always `false`, and present rather than implied: REQ-LIFE-017 asks the report to **state** that no conversion took place, and a field a client can render is a statement where a missing field is an assumption
 * @param currencies every currency that appears anywhere in the report, so a client can lay out columns before reading a row
 * @param dimension `location`, `type` or `tag`
 * @param overlapping whether a thing can appear in more than one row, which is true of tags and false of locations and types. A reader who adds up an overlapping column gets a number that means nothing, and this is what warns them
 * @param rows one per group, largest first by the figure that is present
 */
@Serializable

data class ValuationSummary (

    /* always `false`, and present rather than implied: REQ-LIFE-017 asks the report to **state** that no conversion took place, and a field a client can render is a statement where a missing field is an assumption */
    @SerialName(value = "converted") @Required val converted: kotlin.Boolean,

    /* every currency that appears anywhere in the report, so a client can lay out columns before reading a row */
    @SerialName(value = "currencies") @Required val currencies: kotlin.collections.List<kotlin.String>,

    /* `location`, `type` or `tag` */
    @SerialName(value = "dimension") @Required val dimension: kotlin.String,

    /* whether a thing can appear in more than one row, which is true of tags and false of locations and types. A reader who adds up an overlapping column gets a number that means nothing, and this is what warns them */
    @SerialName(value = "overlapping") @Required val overlapping: kotlin.Boolean,

    /* one per group, largest first by the figure that is present */
    @SerialName(value = "rows") @Required val rows: kotlin.collections.List<ValuationRow>

) {


}

