/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models

import de.greluc.homeinv.client.models.MoneyJson

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * What an item cost, what covers it and what replacing it would cost (REQ-LIFE-001/002/014).  Replaced whole rather than merged, like the attributes and for the same reason: a figure left out is one deliberately cleared, and under a merge \"remove the purchase price\" would have no spelling at all.  Each amount is `{\"amount\":\"49.90\",\"currency\":\"EUR\"`} — a string, never a JSON number, because a number is a `double` by the time it has been through a browser.
 *
 * @param currentValue what it is worth now, or omitted
 * @param currentValueAsOf the day that figure was true
 * @param lifetimeWarranty whether it is covered for life, in which case `warrantyUntil` must be omitted: both is two answers to one question and is refused
 * @param purchase what it cost, or omitted
 * @param purchaseSource where from — a shop, a person, a listing
 * @param purchasedOn when it was bought, or omitted
 * @param replacement what replacing it would cost, or omitted
 * @param replacementAsOf the day that figure was true
 * @param replacementSource `MANUAL` or `PLUGIN`
 * @param warrantyUntil when the warranty ends, or omitted
 */
@Serializable

data class ValuationRequest (

    /* what it is worth now, or omitted */
    @SerialName(value = "currentValue") val currentValue: MoneyJson? = null,

    /* the day that figure was true */
    @SerialName(value = "currentValueAsOf") val currentValueAsOf: kotlinx.datetime.LocalDate? = null,

    /* whether it is covered for life, in which case `warrantyUntil` must be omitted: both is two answers to one question and is refused */
    @SerialName(value = "lifetimeWarranty") val lifetimeWarranty: kotlin.Boolean? = null,

    /* what it cost, or omitted */
    @SerialName(value = "purchase") val purchase: MoneyJson? = null,

    /* where from — a shop, a person, a listing */
    @SerialName(value = "purchaseSource") val purchaseSource: kotlin.String? = null,

    /* when it was bought, or omitted */
    @SerialName(value = "purchasedOn") val purchasedOn: kotlinx.datetime.LocalDate? = null,

    /* what replacing it would cost, or omitted */
    @SerialName(value = "replacement") val replacement: MoneyJson? = null,

    /* the day that figure was true */
    @SerialName(value = "replacementAsOf") val replacementAsOf: kotlinx.datetime.LocalDate? = null,

    /* `MANUAL` or `PLUGIN` */
    @SerialName(value = "replacementSource") val replacementSource: ValuationRequest.ReplacementSource? = null,

    /* when the warranty ends, or omitted */
    @SerialName(value = "warrantyUntil") val warrantyUntil: kotlinx.datetime.LocalDate? = null

) {

    /**
     * `MANUAL` or `PLUGIN`
     *
     * Values: MANUAL,DEPRECIATION,PLUGIN
     */
    @Serializable
    enum class ReplacementSource(val value: kotlin.String) {
        @SerialName(value = "MANUAL") MANUAL("MANUAL"),
        @SerialName(value = "DEPRECIATION") DEPRECIATION("DEPRECIATION"),
        @SerialName(value = "PLUGIN") PLUGIN("PLUGIN");
        override fun toString(): kotlin.String = value
    }

}

