/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models

import de.greluc.homeinv.client.models.FieldDefinitionView

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * One version and the fields it declares.
 *
 * @param fields every field, in display order, inherited ones included once published
 * @param id the version
 * @param ownerId the item type or location category it belongs to
 * @param published whether it is frozen and referenceable
 * @param versionNumber its position in that owner's series, starting at one
 */
@Serializable

data class VersionView (

    /* every field, in display order, inherited ones included once published */
    @SerialName(value = "fields") @Required val fields: kotlin.collections.List<FieldDefinitionView>,

    /* the version */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* the item type or location category it belongs to */
    @SerialName(value = "ownerId") @Required val ownerId: kotlin.String,

    /* whether it is frozen and referenceable */
    @SerialName(value = "published") @Required val published: kotlin.Boolean,

    /* its position in that owner's series, starting at one */
    @SerialName(value = "versionNumber") @Required val versionNumber: kotlin.Int

) {


}

