/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The one condition that decides whether a client shows a field.
 *
 * @param `field` the key of the field watched
 * @param `operator` `equals`, `notEquals`, `present` or `absent`
 * @param `value` the JSON text compared against, for the two operators that compare
 */
@Serializable

data class VisibilityRequest (

    /* the key of the field watched */
    @SerialName(value = "field") @Required val `field`: kotlin.String,

    /* `equals`, `notEquals`, `present` or `absent` */
    @SerialName(value = "operator") @Required val `operator`: kotlin.String,

    /* the JSON text compared against, for the two operators that compare */
    @SerialName(value = "value") val `value`: kotlin.String? = null

) {


}

