/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * When a field is shown: one condition, over one other field of the same item (REQ-CORE-028).  ## Why it is this small  ADR-0020 permits \"a simple condition over another field of the same item\" and gives the example that decides the shape: show `warrantyUntil` when `hasWarranty` is true. It permits no conjunction, no nesting and no reference to a second item — because each of those is a step toward an expression language that would have to evaluate identically in Java, TypeScript and Kotlin, and the line against that is the core of that decision.  A rule is presentation only. A hidden field is not cleared, not exempted from `required` and not removed from the generated schema: hiding a value is not the same as not having one, and a schema that changed shape with the data would be a schema a client could not cache.
 *
 * @param `field` the key of the field this one watches, which must be another field of the same type version — a rule pointing at itself is a refused definition
 * @param `operator` how the watched value is compared
 * @param `value` what it is compared against, as the JSON text of a scalar (`true`, `3`, `\"new\"`). Ignored by {@link Operator#PRESENT Operator#PRESENT} and {@link Operator#ABSENT Operator#ABSENT}
 */
@Serializable

data class VisibilityRule (

    /* the key of the field this one watches, which must be another field of the same type version — a rule pointing at itself is a refused definition */
    @SerialName(value = "field") @Required val `field`: kotlin.String,

    /* how the watched value is compared */
    @SerialName(value = "operator") @Required val `operator`: VisibilityRule.`Operator`,

    /* what it is compared against, as the JSON text of a scalar (`true`, `3`, `\"new\"`). Ignored by {@link Operator#PRESENT Operator#PRESENT} and {@link Operator#ABSENT Operator#ABSENT} */
    @SerialName(value = "value") @Required val `value`: kotlin.String

) {

    /**
     * how the watched value is compared
     *
     * Values: EQUALS,NOT_EQUALS,PRESENT,ABSENT
     */
    @Serializable
    enum class `Operator`(val value: kotlin.String) {
        @SerialName(value = "EQUALS") EQUALS("EQUALS"),
        @SerialName(value = "NOT_EQUALS") NOT_EQUALS("NOT_EQUALS"),
        @SerialName(value = "PRESENT") PRESENT("PRESENT"),
        @SerialName(value = "ABSENT") ABSENT("ABSENT");
        override fun toString(): kotlin.String = value
    }

}

