/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package de.greluc.homeinv.client.apis

import de.greluc.homeinv.client.models.ExportJobView
import de.greluc.homeinv.client.models.Problem

import de.greluc.homeinv.client.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import io.ktor.http.ParametersBuilder
import io.ktor.http.Headers
import io.ktor.http.HttpHeaders
import io.ktor.http.ContentType
import io.ktor.http.content.PartData
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

open class ExportApi : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    /**
     * The archive itself
     * The archive itself.  Streamed rather than buffered: it is tens of megabytes, and holding it in memory to serve it would put the ceiling on how much a tenant may own.
     * @param id the job
     * @return de.greluc.homeinv.client.infrastructure.OctetByteArray
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun content(id: kotlin.String): HttpResponse<de.greluc.homeinv.client.infrastructure.OctetByteArray> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/export-jobs/{id}/content".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * One export job, which is how progress is watched.
     * One export job, which is how progress is watched.
     * @param id which one
     * @return ExportJobView
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun job1(id: kotlin.String): HttpResponse<ExportJobView> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/export-jobs/{id}".replace("{" + "id" + "}", "$id"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * This tenant&#39;s export jobs, newest first.
     * This tenant&#39;s export jobs, newest first.
     * @param limit how many at most; capped at 200 (optional, default to 50)
     * @return kotlin.collections.List<ExportJobView>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun listJobs1(limit: kotlin.Int? = 50): HttpResponse<kotlin.collections.List<ExportJobView>> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        limit?.apply { localVariableQuery["limit"] = listOf("$limit") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v1/export-jobs",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<ListJobs1Response>().map { value }
    }

    @Serializable(ListJobs1Response.Companion::class)
    private class ListJobs1Response(val value: List<ExportJobView>) {
        companion object : KSerializer<ListJobs1Response> {
            private val serializer: KSerializer<List<ExportJobView>> = serializer<List<ExportJobView>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: ListJobs1Response) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = ListJobs1Response(serializer.deserialize(decoder))
        }
    }

    /**
     * Asks for an export (REQ-PORT-005).
     * Asks for an export (REQ-PORT-005).
     * @return ExportJobView
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun requestExport(): HttpResponse<ExportJobView> {

        val localVariableAuthNames = listOf<String>()

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v1/export-jobs",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


}
