/*
 * SPDX-FileCopyrightText: Lucas Greuloch
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

/**
 * Computes the Content-Security-Policy from the built bundle and writes the
 * server configuration that emits it.
 *
 * ADR-0038 decides three things this script implements:
 *
 *  1. **`web` serves the headers**, not the operator's reverse proxy. A header an
 *     operator writes into their own config cannot be tested here, and a policy
 *     nobody tests drifts until the first `unsafe-inline` appears to make
 *     something work.
 *  2. **Hashes, not nonces.** The inline content is fixed at build time, so the
 *     policy can name exactly what is authorised rather than authorising whatever
 *     arrives with the right nonce.
 *  3. **`trusted-types default` beside `require-trusted-types-for 'script'`.** On
 *     its own the requirement leaves policy *creation* unrestricted, so anything
 *     achieving script execution can mint its own policy and satisfy the check.
 *     Naming the one policy this bundle creates closes that.
 *
 * `--check` recomputes and compares instead of writing. CI runs it, so a policy
 * that no longer matches its bundle fails the build rather than failing a user's
 * browser — the same drift mechanism as `deploy/services.yaml`.
 */

import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const builtIndex = join(root, "dist", "index.html");
const nginxConf = join(root, "nginx", "default.conf");

/**
 * The base64 SHA-256 of a string, in the form a CSP hash source takes.
 *
 * The hash covers the element's content exactly as it appears between the tags —
 * every space and newline included. That is why a single character changed in the
 * bootstrap changes the hash, which is the coupling this whole mechanism relies
 * on.
 *
 * @param {string} content the element's text content
 * @returns {string} the `sha256-…` source expression
 */
function hashOf(content) {
  return `'sha256-${createHash("sha256").update(content, "utf8").digest("base64")}'`;
}

/**
 * Extracts the content of every inline element of one kind.
 *
 * @param {string} html the built document
 * @param {"script"|"style"} tag which element
 * @returns {string[]} the contents, in document order
 */
function inlineContents(html, tag) {
  const pattern = new RegExp(`<${tag}(?![^>]*\\bsrc=)[^>]*>([\\s\\S]*?)</${tag}>`, "g");
  return [...html.matchAll(pattern)].map((match) => match[1]);
}

if (!existsSync(builtIndex)) {
  console.error(`${builtIndex} is missing. Run the build first.`);
  process.exit(1);
}

const html = readFileSync(builtIndex, "utf8");
const scriptHashes = inlineContents(html, "script").map(hashOf);
const styleHashes = inlineContents(html, "style").map(hashOf);

if (scriptHashes.length === 0) {
  // The theme bootstrap is the one inline script and it must be there: without it
  // a light-preferring user sees a dark flash on every load (ADR-0033). Its
  // absence means the build dropped it, which is worth failing over.
  console.error("No inline script found in the built index.html. The theme bootstrap is missing.");
  process.exit(1);
}

const policy = [
  // Nothing is allowed that is not named. `default-src 'none'` rather than
  // `'self'`, so a directive forgotten below fails closed instead of inheriting
  // a permissive default.
  "default-src 'none'",
  `script-src 'self' ${scriptHashes.join(" ")}`,
  `style-src 'self'${styleHashes.length > 0 ? " " + styleHashes.join(" ") : ""}`,
  // The media hostname is a separate origin, and signed URLs point at it.
  "img-src 'self' data: blob:",
  "font-src 'self'",
  // Same origin only. REQ-PRIV-015 allows no third-party host at all, and this is
  // where a violation of it would actually be stopped rather than merely
  // discouraged.
  "connect-src 'self'",
  "manifest-src 'self'",
  "worker-src 'self'",
  // Nothing embeds us and we embed nothing.
  "frame-ancestors 'none'",
  "frame-src 'none'",
  "object-src 'none'",
  "base-uri 'none'",
  "form-action 'self'",
  "require-trusted-types-for 'script'",
  "trusted-types default",
  "upgrade-insecure-requests",
].join("; ");

const conf = `# GENERATED BY scripts/csp.mjs — DO NOT EDIT.
#
# The hashes below are computed from the built bundle. Change the inline
# bootstrap in index.html and this file must be regenerated; \`npm run csp:check\`
# fails until it is, which is the intended coupling (ADR-0038).

server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # ADR-0038: the shell and every security header come from this container, so
    # the policy is in the repository and can be compared against an expected
    # string in CI (REQ-SEC-060).
    add_header Content-Security-Policy "${policy}" always;

    # HSTS without preload: \`max-age\` and \`includeSubDomains\` carry the
    # protection and cover the media and plugin subdomains this design creates.
    # Preload is a one-way door on a domain an operator may also use for other
    # things (O20).
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Cross-Origin-Opener-Policy "same-origin" always;
    add_header Cross-Origin-Resource-Policy "same-origin" always;
    # No COEP: ADR-0040 drops it, and REQ-SEC-061 makes CI fail if it reappears.
    add_header Permissions-Policy "camera=(self), geolocation=(), microphone=(), payment=(), usb=()" always;

    # Hashed filenames, so a year is safe and a release invalidates by name.
    location /assets/ {
        add_header Cache-Control "public, max-age=31536000, immutable" always;
        try_files \\$uri =404;
    }

    # The shell itself is never cached: it names the hashed assets, and a stale
    # copy points at files that no longer exist.
    location = /index.html {
        add_header Cache-Control "no-cache" always;
    }

    location / {
        try_files \\$uri \\$uri/ /index.html;
    }
}
`;

const check = process.argv.includes("--check");
if (check) {
  const current = existsSync(nginxConf) ? readFileSync(nginxConf, "utf8") : "";
  if (current !== conf) {
    console.error("The served CSP does not match the built bundle.");
    console.error("Run `npm run build` and commit nginx/default.conf.");
    process.exit(1);
  }
  console.log("The served CSP matches the built bundle.");
} else {
  writeFileSync(nginxConf, conf, "utf8");
  console.log(`Wrote ${nginxConf}`);
  console.log(`  script hashes: ${scriptHashes.length}, style hashes: ${styleHashes.length}`);
}
