/*
 * SPDX-FileCopyrightText: Lucas Greuloch
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
package de.greluc.homeinv.plugin.oidc;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * The image carries the licence notice of what is in it (REQ-CON-013).
 *
 * <p>A permissive licence asks for its notice in <b>every copy</b>, and a container image is a
 * copy. The notice is generated by {@code tools/notices.py} from the jars {@code installDist}
 * writes into {@code lib/} and packaged as a resource here, which is what {@code --licences}
 * prints.
 *
 * <p>What this test is actually for is the packaging: the file is in {@code src/main/resources},
 * and a resource that stops being packaged fails nothing at compile time and answers nothing at
 * runtime — a flag that prints an empty notice looks like a flag that works.
 */
@DisplayName("The licence notice this plugin ships")
class LicenceNoticeTest {

  @Test
  @DisplayName("is on the classpath, and is the notice rather than an empty file")
  void theNoticeIsPackaged() throws IOException {
    try (InputStream notice = Main.class.getResourceAsStream("/THIRD-PARTY-NOTICES.txt")) {
      assertThat(notice)
          .as("`python tools/notices.py plugin-oidc` generates it; it is committed")
          .isNotNull();
      String text = new String(notice.readAllBytes(), StandardCharsets.UTF_8);

      assertThat(text).startsWith("THIRD-PARTY LICENCE NOTICES");
      assertThat(text).contains("grpc-api");
      assertThat(text)
          .as("a notice this short is a generator that failed")
          .hasSizeGreaterThan(10_000);
    }
  }
}
