# SPDX-FileCopyrightText: Lucas Greuloch
# SPDX-License-Identifier: AGPL-3.0-or-later

spring:
  main:
    web-application-type: none
    lazy-initialization: true

  datasource:
    url: ${HOMEINV_DB_URL:jdbc:postgresql://localhost:5432/homeinv}
    username: ${HOMEINV_DB_MIGRATION_USER:homeinv_migrator}
    password: ${homeinv.secret.db-migration-password}
    hikari:
      maximum-pool-size: 2
      pool-name: homeinv-migrate

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: false

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

management:
  endpoint:
    health:
      group:
        readyz:
          include: readinessState,db

  server:
    port: -1
