/*
 * SPDX-FileCopyrightText: Lucas Greuloch
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
package de.greluc.homeinv.identity.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Version;
import java.time.Instant;
import java.util.UUID;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * Something an account authenticates with besides its password (REQ-AUTH-002).
 *
 * <p>Instance-wide for {@link AppUser}'s reason, sharpened: the second factor is asked for between
 * the password and the session, when there is no tenant yet to scope a policy with. It is the
 * seventh entry on the closed list in {@code 07 §7.1}, and what protects it instead is that it is
 * reachable only through the caller's own session — no endpoint takes a user id, and an instance
 * operator has no path to somebody else's authenticator either.
 *
 * <p>One row is one authenticator: a TOTP secret, or a single recovery code. Ten recovery codes are
 * ten rows, because each is spent on its own and a column holding ten of them would be a list that
 * has to be rewritten to cross one off.
 */
@Entity
@Table(schema = "identity", name = "credential")
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class Credential {

  /** A time-based one-time password, RFC 6238. */
  public static final String TOTP = "TOTP";

  /** One single-use code for an account that has lost its authenticator. */
  public static final String RECOVERY_CODE = "RECOVERY_CODE";

  @Id
  @Column(name = "id", nullable = false, updatable = false)
  private UUID id;

  /** Whose credential this is. */
  @Column(name = "user_id", nullable = false, updatable = false)
  private UUID userId;

  /** {@link #TOTP} or {@link #RECOVERY_CODE}; {@code PASSKEY} arrives with WebAuthn. */
  @Column(name = "kind", nullable = false, updatable = false)
  private String kind;

  /** What the person calls this authenticator, or null. */
  @Column(name = "label")
  private String label;

  /**
   * The sealed TOTP secret, or the Argon2id hash of a recovery code.
   *
   * <p>Never the value itself in either case, and never returned by any endpoint: the secret is
   * shown once during enrolment, from the call that generated it, and is unreadable afterwards
   * without the instance's credential key.
   *
   * <p>Not exposed through the class-level {@code @Getter}, for {@code AppUser.passwordHash}'s
   * reason: a getter on a whole class is how a secret ends up in a log line.
   */
  @Getter(AccessLevel.NONE)
  @Column(name = "material", nullable = false)
  private String material;

  /** When a code generated from this secret first proved it, or null while unconfirmed. */
  @Column(name = "confirmed_at")
  private Instant confirmedAt;

  /** When a code from it was last accepted — the replay guard, and for a recovery code the spend. */
  @Column(name = "last_used_at")
  private Instant lastUsedAt;

  @Column(name = "created_at", nullable = false, updatable = false)
  private Instant createdAt;

  @Column(name = "updated_at", nullable = false)
  private Instant updatedAt;

  @Column(name = "created_by", updatable = false)
  private UUID createdBy;

  @Column(name = "updated_by")
  private UUID updatedBy;

  /** When it was removed. A tombstone, because "who could sign in, and when" is an audit question. */
  @Column(name = "deleted_at")
  private Instant deletedAt;

  @Version
  @Column(name = "version", nullable = false)
  private long version;

  /**
   * Enrols an authenticator, unconfirmed.
   *
   * @param userId whose it is
   * @param kind {@link #TOTP} or {@link #RECOVERY_CODE}
   * @param material the sealed secret or the hash of a code
   * @param label what to call it, or null
   * @param now the enrolment instant
   * @return the new credential, which no login accepts until it is confirmed
   */
  public static Credential enrol(
      UUID userId, String kind, String material, String label, Instant now) {
    Credential credential = new Credential();
    credential.id = UUID.randomUUID();
    credential.userId = userId;
    credential.kind = kind;
    credential.material = material;
    credential.label = label;
    credential.createdAt = now;
    credential.updatedAt = now;
    credential.createdBy = userId;
    credential.updatedBy = userId;
    return credential;
  }

  /**
   * A recovery code, which counts from the moment it is issued.
   *
   * <p>Confirmed on creation, unlike a TOTP secret: a recovery code is generated by this system
   * rather than copied into another one, so there is nothing for the account holder to prove.
   *
   * @param userId whose it is
   * @param hash the Argon2id hash of the code
   * @param now the issuing instant
   * @return the new credential
   */
  public static Credential recoveryCode(UUID userId, String hash, Instant now) {
    Credential credential = enrol(userId, RECOVERY_CODE, hash, null, now);
    credential.confirmedAt = now;
    return credential;
  }

  /**
   * The sealed secret or the hash.
   *
   * @return the stored material, which is of no use without the instance's credential key
   */
  public String material() {
    return material;
  }

  /**
   * Whether a login may be completed with this.
   *
   * @return true when it is confirmed and not removed
   */
  public boolean isUsable() {
    return confirmedAt != null && deletedAt == null;
  }

  /**
   * Whether this recovery code has been spent.
   *
   * @return true when it has been used once, which is all a recovery code gets
   */
  public boolean isSpent() {
    return lastUsedAt != null;
  }

  /**
   * Records that a code from this credential was accepted.
   *
   * @param now when it was accepted
   */
  public void used(Instant now) {
    used(now, now);
  }

  /**
   * Records an acceptance whose replay guard is not the moment it happened.
   *
   * <p>For TOTP the caller passes the <b>start of the accepted time step</b>, which is what the
   * guard compares against (RFC 6238 §5.2): a code typed a little early belongs to the next step,
   * and storing the moment it arrived would leave that code replayable for the rest of its own
   * step. For a recovery code the two are the same instant, and {@link #used(Instant)} says so.
   *
   * @param spent what is now spent — for TOTP the start of the accepted step
   * @param now when the acceptance happened
   */
  public void used(Instant spent, Instant now) {
    this.lastUsedAt = spent;
    this.updatedAt = now;
  }

  /**
   * Confirms an enrolment.
   *
   * @param now when the first code proved the secret
   */
  public void confirm(Instant now) {
    this.confirmedAt = now;
    this.updatedAt = now;
  }

  /**
   * Removes it, leaving the tombstone.
   *
   * @param actor who removed it
   * @param now when
   */
  public void remove(UUID actor, Instant now) {
    this.deletedAt = now;
    this.updatedAt = now;
    this.updatedBy = actor;
  }
}
