/*
 * SPDX-FileCopyrightText: Lucas Greuloch
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
package de.greluc.homeinv.crypto.infrastructure;

import de.greluc.homeinv.crypto.api.SensitiveValues;
import de.greluc.homeinv.platform.TenantContext;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.security.GeneralSecurityException;
import java.security.SecureRandom;
import java.util.Base64;
import java.util.Optional;
import java.util.UUID;
import javax.crypto.Cipher;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

/**
 * The stored format of a sealed field, byte for byte (ADR-0019).
 *
 * <pre>
 *  offset  size  field
 *  ------  ----  --------------------------------------------------------------
 *       0     1  format version, currently 0x01
 *       1     1  dek_id — which of this tenant's data key versions sealed it
 *       2    12  nonce, from a CSPRNG, never reused under one key
 *      14     n  ciphertext (AES-256-GCM)
 *    14+n    16  authentication tag
 * </pre>
 *
 * <p>The two header bytes are <b>authenticated, not merely present</b>: they are the first two
 * bytes of the AAD. A ciphertext therefore cannot be replayed into a deployment that reads a later
 * format version, and {@code dek_id} cannot be flipped to point at another key.
 *
 * <pre>
 * AAD = version(1) ‖ dek_id(1) ‖ tenantId(16) ‖ entityId(16) ‖ len(fieldKey) u16be ‖ fieldKey(UTF-8)
 * </pre>
 *
 * <p>{@code fieldKey} is <b>length-prefixed</b>, and that is the part worth spelling out: the AAD
 * has to be an unambiguous encoding of the tuple. Plain concatenation is unambiguous today only
 * because the one variable-length member sits last — so the first time somebody appends a field to
 * this AAD, two different tuples would start producing the same bytes and the guarantee would be
 * gone with no visible symptom. Two bytes remove the trap now.
 *
 * <p>What this deliberately does not do: no key commitment, because every key here is generated by
 * the server and never attacker-supplied; and <b>no compression before encryption, ever</b> —
 * compressing attacker-influenced plaintext beside a secret is the CRIME/BREACH shape, and licence
 * keys sit in the same JSONB document as free text.
 */
@Component
@RequiredArgsConstructor
public class EnvelopeCrypto implements SensitiveValues {

  /** The format this code writes. A value with another version is read by another version. */
  private static final byte FORMAT_VERSION = 0x01;

  /** The nonce length GCM is specified for. */
  private static final int IV_BYTES = 12;

  /** The tag length in bits, and the longest GCM offers. */
  private static final int TAG_BITS = 128;

  /** Where the ciphertext starts: two header bytes and the nonce. */
  private static final int HEADER_BYTES = 2 + IV_BYTES;

  /** The shortest a sealed value can be: the header plus an empty ciphertext's tag. */
  private static final int MINIMUM_BYTES = HEADER_BYTES + TAG_BITS / 8;

  private final TenantDataKeys keys;
  private final SecureRandom random = new SecureRandom();

  @Override
  @Transactional(propagation = Propagation.REQUIRED)
  public String seal(UUID entityId, String fieldKey, String plaintext) {
    UUID tenantId = TenantContext.require();
    TenantDataKeys.DataKey dataKey = keys.active();

    byte[] iv = new byte[IV_BYTES];
    random.nextBytes(iv);
    byte[] aad = aad(dataKey.dekId(), tenantId, entityId, fieldKey);

    try {
      Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
      cipher.init(Cipher.ENCRYPT_MODE, dataKey.key(), new GCMParameterSpec(TAG_BITS, iv));
      cipher.updateAAD(aad);
      byte[] sealed = cipher.doFinal(plaintext.getBytes(StandardCharsets.UTF_8));

      byte[] out =
          ByteBuffer.allocate(HEADER_BYTES + sealed.length)
              .put(FORMAT_VERSION)
              .put((byte) dataKey.dekId())
              .put(iv)
              .put(sealed)
              .array();
      return Base64.getUrlEncoder().withoutPadding().encodeToString(out);
    } catch (GeneralSecurityException failed) {
      throw new IllegalStateException("A sensitive value could not be sealed.", failed);
    }
  }

  @Override
  @Transactional(propagation = Propagation.REQUIRED, readOnly = true)
  public String open(UUID entityId, String fieldKey, String sealed) {
    UUID tenantId = TenantContext.require();
    byte[] raw =
        decode(sealed)
            .orElseThrow(
                () -> new IllegalStateException("A stored value is not in the sealed format."));
    int dekId = Byte.toUnsignedInt(raw[1]);
    SecretKeySpec key = keys.of(dekId);

    try {
      Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
      cipher.init(Cipher.DECRYPT_MODE, key, new GCMParameterSpec(TAG_BITS, raw, 2, IV_BYTES));
      cipher.updateAAD(aad(dekId, tenantId, entityId, fieldKey));
      byte[] plain = cipher.doFinal(raw, HEADER_BYTES, raw.length - HEADER_BYTES);
      return new String(plain, StandardCharsets.UTF_8);
    } catch (GeneralSecurityException failed) {
      // Altered, moved to another field, moved to another record, moved to
      // another tenant: one answer for all of them, because the answer to all of
      // them is the same and telling them apart would be telling an attacker
      // which of the four they had managed.
      throw new IllegalStateException(
          "A sensitive value did not verify. It was altered, or it does not belong to this "
              + "tenant, this record and this field.",
          failed);
    }
  }

  @Override
  public boolean isSealed(String value) {
    return decode(value).isPresent();
  }

  // -------------------------------------------------------------------------

  /**
   * The bytes of a sealed value, when it is one.
   *
   * <p>Empty rather than null for anything that is not: this is asked of every stored value on the
   * path where a field has just been marked sensitive and older rows still hold plaintext, and
   * "not sealed" is an ordinary answer there rather than an error.
   *
   * @param value a stored attribute value
   * @return the decoded bytes, or empty when the value is not in this format
   */
  private static Optional<byte[]> decode(String value) {
    if (value == null || value.length() < 4) {
      return Optional.empty();
    }
    byte[] raw;
    try {
      raw = Base64.getUrlDecoder().decode(value);
    } catch (IllegalArgumentException notBase64) {
      return Optional.empty();
    }
    if (raw.length < MINIMUM_BYTES || raw[0] != FORMAT_VERSION) {
      return Optional.empty();
    }
    return Optional.of(raw);
  }

  /**
   * {@code version ‖ dek_id ‖ tenantId ‖ entityId ‖ len(fieldKey) ‖ fieldKey}.
   *
   * @param dekId the data key version
   * @param tenantId the tenant
   * @param entityId the item or location
   * @param fieldKey the attribute key
   * @return the additional authenticated data
   */
  private static byte[] aad(int dekId, UUID tenantId, UUID entityId, String fieldKey) {
    byte[] field = fieldKey.getBytes(StandardCharsets.UTF_8);
    if (field.length > 0xffff) {
      throw new IllegalArgumentException("A field key of " + field.length + " bytes is not one.");
    }
    return ByteBuffer.allocate(1 + 1 + 16 + 16 + 2 + field.length)
        .put(FORMAT_VERSION)
        .put((byte) dekId)
        .putLong(tenantId.getMostSignificantBits())
        .putLong(tenantId.getLeastSignificantBits())
        .putLong(entityId.getMostSignificantBits())
        .putLong(entityId.getLeastSignificantBits())
        .putShort((short) field.length)
        .put(field)
        .array();
  }
}
