#!/usr/bin/env python3
# SPDX-FileCopyrightText: Lucas Greuloch
# SPDX-License-Identifier: AGPL-3.0-or-later

"""Generates the persisted-query allowlist the GraphQL surface serves (REQ-API-006).

WHY THE LIST COMES FROM THE BUILD

08 §8.4 asks for "in production only registered queries". Where the register
lives decides what the safeguard is worth, and this project's answer is: beside
the client that sends them, generated by the build that ships both (ADR-0079).

  * A REGISTRATION ENDPOINT would let whoever may query also register, which is
    the safeguard removing itself.
  * AUTOMATIC PERSISTED QUERIES (the Apollo pattern) are the same thing wearing a
    hash: the first request carries the query and the server remembers it.
  * A TABLE PER TENANT is a table, a permission and a screen, for a list that
    changes when the client changes and at no other time.

So this reads every `.graphql` document under `web/src`, hashes it exactly as
`QueryGuard.hashOf` does -- SHA-256 over the stripped text, lower-case hex -- and
writes the list into the application's resources. A client that sends something
the build did not see is refused where somebody is watching.

TODAY IT FINDS NOTHING, and that is not a failure. `web/` speaks REST; when its
first GraphQL document is written, this file fills itself and the check below
starts having something to compare. Until then the surface answers
administrators, which is what `QueryGuard` says at startup.

USAGE

    python tools/persisted_queries.py           # write the list
    python tools/persisted_queries.py --check    # fail if the list is stale
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CLIENT = ROOT / "web" / "src"
REGISTRY = ROOT / "app" / "src" / "main" / "resources" / "graphql" / "persisted-queries.txt"

HEADER = """# GENERATED BY tools/persisted_queries.py - DO NOT EDIT.
#
# The SHA-256 of every GraphQL document the client ships, which is the complete
# list of queries this release serves to a non-administrator (REQ-API-006,
# ADR-0079). One hash per line, lower case, with the document it came from beside
# it for a reader.
#
# `QueryGuard` reads this at startup and hashes what a client sends the same way:
# SHA-256 over the stripped text. Re-generate it with the command above whenever a
# document changes; CI runs `--check` and fails while the two disagree.
"""


def documents() -> list[Path]:
    """Every GraphQL document the client holds, in a stable order."""
    if not CLIENT.exists():
        return []
    return sorted(CLIENT.rglob("*.graphql"))


def rendered() -> str:
    """The file as it should be, from the documents as they are."""
    lines = [HEADER]
    for document in documents():
        text = document.read_text(encoding="utf-8").strip()
        digest = hashlib.sha256(text.encode("utf-8")).hexdigest()
        lines.append(f"{digest}  {document.relative_to(ROOT).as_posix()}")
    if len(lines) == 1:
        lines.append("# (no GraphQL document in web/src yet)")
    return "\n".join(lines) + "\n"


def main() -> int:
    """Writes the list, or compares it and reports the difference."""
    expected = rendered()
    checking = "--check" in sys.argv

    if checking:
        actual = REGISTRY.read_text(encoding="utf-8") if REGISTRY.exists() else ""
        if actual != expected:
            print(
                "The persisted-query allowlist does not match the client's documents.\n"
                "Run `python tools/persisted_queries.py` and commit the result, so that a query\n"
                "the build has not seen is refused here rather than in somebody's browser."
            )
            return 1
        print(f"{len(documents())} persisted quer(ies); the allowlist matches the client.")
        return 0

    REGISTRY.parent.mkdir(parents=True, exist_ok=True)
    REGISTRY.write_text(expected, encoding="utf-8", newline="\n")
    print(f"Wrote {REGISTRY.relative_to(ROOT).as_posix()} with {len(documents())} quer(ies).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
