/*
 * SPDX-FileCopyrightText: Lucas Greuloch
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
package de.greluc.homeinv.tenancy.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Version;
import java.time.Instant;
import java.util.UUID;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * A tenant: the boundary every other row in the system belongs inside.
 *
 * <p>The {@code tenant_id} column is generated by the database from {@code id}, so the table obeys
 * the same rule as every other domain table — it carries a discriminator and a policy — without the
 * application having to write the same value twice. It is mapped read-only here for that reason: a
 * write would be rejected by PostgreSQL, and mapping it writable would produce that rejection as a
 * confusing error at the first insert rather than as an obvious one here.
 */
@Entity
@Table(schema = "tenancy", name = "tenant")
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class Tenant {

  @Id
  @Column(name = "id", nullable = false, updatable = false)
  private UUID id;

  /** Generated by the database as a copy of {@link #id}; never written from here. */
  @Column(name = "tenant_id", insertable = false, updatable = false)
  private UUID tenantId;

  /** The name shown in the UI. Never blank. */
  @Column(name = "name", nullable = false)
  private String name;

  /** The tenant's default UI language, used for a new member who has expressed no preference. */
  @Column(name = "locale", nullable = false)
  private String locale;

  /**
   * {@code ACTIVE}, {@code SUSPENDED} or {@code PENDING_DELETION} (REQ-TEN-011).
   *
   * <p>The last two are both <em>inaccessible</em> and the API answers them identically, with one
   * token: which of the two a tenant is in is a status oracle over a boundary REQ-SEC-025 closes
   * (open point O26).
   */
  @Column(name = "lifecycle_state", nullable = false)
  private String lifecycleState = "ACTIVE";

  @Column(name = "deletion_requested_at")
  private Instant deletionRequestedAt;

  @Column(name = "deletion_requested_by")
  private UUID deletionRequestedBy;

  /**
   * The SHA-256 of the token that withdraws an erasure request (REQ-SEC-048).
   *
   * <p>A hash and not the token: a leaked database is not a set of working revocations. The value
   * itself exists once, in the answer to the request.
   */
  @Column(name = "revocation_token_hash")
  private String revocationTokenHash;

  @Column(name = "created_at", nullable = false, updatable = false)
  private Instant createdAt;

  @Column(name = "updated_at", nullable = false)
  private Instant updatedAt;

  @Column(name = "created_by", updatable = false)
  private UUID createdBy;

  @Column(name = "updated_by")
  private UUID updatedBy;

  @Column(name = "deleted_at")
  private Instant deletedAt;

  @Version
  @Column(name = "version", nullable = false)
  private long version;

  private Tenant(UUID id, String name, Instant now) {
    this.id = id;
    this.name = name;
    this.locale = "de";
    this.createdAt = now;
    this.updatedAt = now;
  }

  /**
   * Creates a tenant.
   *
   * @param id the identifier, chosen before the row exists because the row-level security policy
   *     compares against it (see {@code TenantProvisioningService})
   * @param name the display name; must not be blank
   * @param now the creation instant
   * @return the new tenant, not yet persisted
   */
  public static Tenant create(UUID id, String name, Instant now) {
    if (name == null || name.isBlank()) {
      throw new IllegalArgumentException("A tenant needs a name");
    }
    return new Tenant(id, name, now);
  }

  /**
   * Whether this tenant answers at all.
   *
   * @return {@code true} only while it is {@code ACTIVE}
   */
  public boolean isAccessible() {
    return "ACTIVE".equals(lifecycleState);
  }

  /**
   * Whether an erasure has been asked for and not withdrawn.
   *
   * @return {@code true} while the grace period runs
   */
  public boolean isPendingDeletion() {
    return "PENDING_DELETION".equals(lifecycleState);
  }

  /**
   * Records an erasure request (REQ-TEN-011).
   *
   * <p>The state, the instant and the token move together, and the table's check constraint says
   * so: a {@code PENDING_DELETION} with no timestamp would be a grace period that never elapses,
   * and one with no token would be a request nobody can withdraw.
   *
   * @param tokenHash the SHA-256 of the revocation token
   * @param actor the owner asking
   * @param now the instant of the request
   */
  public void requestDeletion(String tokenHash, UUID actor, Instant now) {
    this.lifecycleState = "PENDING_DELETION";
    this.deletionRequestedAt = now;
    this.deletionRequestedBy = actor;
    this.revocationTokenHash = tokenHash;
    this.updatedBy = actor;
    this.updatedAt = now;
  }

  /**
   * Withdraws the request and makes the tenant answer again.
   *
   * <p>The token is cleared with it. A token that survived its own revocation would be a second
   * withdrawal of a request that no longer exists, and the next request gets a token of its own.
   *
   * @param now the instant of the withdrawal
   */
  public void revokeDeletion(Instant now) {
    this.lifecycleState = "ACTIVE";
    this.deletionRequestedAt = null;
    this.deletionRequestedBy = null;
    this.revocationTokenHash = null;
    this.updatedAt = now;
  }
}
