/*
 * SPDX-FileCopyrightText: Lucas Greuloch
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
package de.greluc.homeinv.tenancy.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Version;
import java.time.Instant;
import java.util.UUID;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * A tenant: the boundary every other row in the system belongs inside.
 *
 * <p>The {@code tenant_id} column is generated by the database from {@code id}, so the table obeys
 * the same rule as every other domain table — it carries a discriminator and a policy — without the
 * application having to write the same value twice. It is mapped read-only here for that reason: a
 * write would be rejected by PostgreSQL, and mapping it writable would produce that rejection as a
 * confusing error at the first insert rather than as an obvious one here.
 */
@Entity
@Table(schema = "tenancy", name = "tenant")
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class Tenant {

  @Id
  @Column(name = "id", nullable = false, updatable = false)
  private UUID id;

  /** Generated by the database as a copy of {@link #id}; never written from here. */
  @Column(name = "tenant_id", insertable = false, updatable = false)
  private UUID tenantId;

  /** The name shown in the UI. Never blank. */
  @Column(name = "name", nullable = false)
  private String name;

  /** The tenant's default UI language, used for a new member who has expressed no preference. */
  @Column(name = "locale", nullable = false)
  private String locale;

  @Column(name = "created_at", nullable = false, updatable = false)
  private Instant createdAt;

  @Column(name = "updated_at", nullable = false)
  private Instant updatedAt;

  @Column(name = "created_by", updatable = false)
  private UUID createdBy;

  @Column(name = "updated_by")
  private UUID updatedBy;

  @Column(name = "deleted_at")
  private Instant deletedAt;

  @Version
  @Column(name = "version", nullable = false)
  private long version;

  private Tenant(UUID id, String name, Instant now) {
    this.id = id;
    this.name = name;
    this.locale = "de";
    this.createdAt = now;
    this.updatedAt = now;
  }

  /**
   * Creates a tenant.
   *
   * @param id the identifier, chosen before the row exists because the row-level security policy
   *     compares against it (see {@code TenantProvisioningService})
   * @param name the display name; must not be blank
   * @param now the creation instant
   * @return the new tenant, not yet persisted
   */
  public static Tenant create(UUID id, String name, Instant now) {
    if (name == null || name.isBlank()) {
      throw new IllegalArgumentException("A tenant needs a name");
    }
    return new Tenant(id, name, now);
  }
}
